import { z } from 'zod';

// GET /api/dashboard 응답
export const DashboardSummarySchema = z.object({
  summary: z.object({
    todayRevenue: z.number(),
    todayOrders: z.number(),
    monthlyRevenue: z.number(),
    monthlyProfit: z.number(),
    adRate: z.number(),
    totalProducts: z.number(),
    roas: z.number(),
    ctr: z.number(),
    adRevenue: z.number(),
    totalAdSpend: z.number(),
    prevMonthlyRevenue: z.number(),
    prevMonthlyProfit: z.number(),
    prevRoas: z.number(),
    prevCtr: z.number(),
    prevAdRevenue: z.number(),
    prevTotalAdSpend: z.number(),
    prevAdRate: z.number(),
  }),
  gradeCount: z.record(z.number()),
  alerts: z.array(z.any()),
  warnings: z.object({
    minusProducts: z.number(),
    lowProfitProducts: z.number(),
    highAdProducts: z.number(),
    needReorder: z.number(),
    lowCtrProducts: z.number().optional(),
    lowReviewProducts: z.number().optional(),
  }),
  topProducts: z.array(z.object({
    id: z.string(),
    name: z.string(),
    company: z.string(),
    grade: z.string(),
    revenue: z.number(),
    netProfit: z.number(),
    profitRate: z.number(),
  })),
  monthlyTrend: z.array(z.object({
    period: z.string(),
    revenue: z.number(),
    profit: z.number(),
    adCost: z.number(),
  })),
  profitDetail: z.object({
    revenue: z.number(),
    costOfGoods: z.number(),
    commission: z.number(),
    shippingCost: z.number(),
    adCost: z.number(),
    otherCost: z.number(),
    netProfit: z.number(),
    orderCount: z.number(),
  }).optional(),
  rangeKpi: z.object({
    range: z.string(),
    revenue: z.number(),
    profit: z.number(),
    adSpend: z.number(),
    prevRevenue: z.number(),
    prevProfit: z.number(),
    revenueChange: z.number(),
    profitChange: z.number(),
    adRoas: z.number(),
    adConvRevenue: z.number(),
    profitRate: z.number().optional(),
    adRate: z.number().optional(),
    adCost: z.number().optional(),
    prevProfitRate: z.number().optional(),
    prevAdRate: z.number().optional(),
    prevAdCost: z.number().optional(),
    profitRateChange: z.number().optional(),
    adRateChange: z.number().optional(),
    adCtr: z.number().optional(),
    prevAdSpend: z.number().optional(),
    prevAdConvRevenue: z.number().optional(),
    prevAdRoas: z.number().optional(),
    prevAdCtr: z.number().optional(),
    adSpendChange: z.number().optional(),
    adConvRevenueChange: z.number().optional(),
    adRoasChange: z.number().optional(),
    adCtrChange: z.number().optional(),
  }).optional(),
  trafficKpi: z.object({
    visitors: z.number(),
    views: z.number(),
    orders: z.number(),
    salesQty: z.number(),
    revenue: z.number(),
    cartAdds: z.number(),
    date: z.string().optional(),
    periodDays: z.number().optional(),
    productCount: z.number().optional(),
    conversionRate: z.number().optional(),
    adSummary: z.record(z.any()).nullable().optional(),
    source: z.string().optional(),
    netProfit: z.number().optional(),
    profitRate: z.number().optional(),
    costCoverage: z.number().optional(),
    needsScrape: z.boolean().optional(),
  }).optional(),
  adKpi: z.object({
    totalSpend: z.number(),
    impressions: z.number(),
    clicks: z.number(),
    convRevenue: z.number(),
    ctr: z.number(),
    roas: z.number(),
    conversions: z.number().optional(),
    cvr: z.number().optional(),
    prevSpend: z.number().optional(),
    prevConvRevenue: z.number().optional(),
    prevCtr: z.number().optional(),
    prevRoas: z.number().optional(),
    spendChange: z.number().optional(),
    convRevenueChange: z.number().optional(),
    roasChange: z.number().optional(),
    ctrChange: z.number().optional(),
    totalRevenue: z.number().optional(),
  }).optional(),
  comparison: z.object({
    prevRevenue: z.number(),
    prevProfit: z.number(),
    revenueChange: z.number(),
    profitChange: z.number(),
    prevAdCost: z.number().optional(),
    prevAdRate: z.number().optional(),
    prevProfitRate: z.number().optional(),
    adRateChange: z.number().optional(),
    profitRateChange: z.number().optional(),
    adSaving: z.number().optional(),
  }).optional(),
  dailyTrend: z.array(z.object({
    date: z.string(),
    revenue: z.number(),
    adCost: z.number(),
    profitRate: z.number().optional(),
    adRate: z.number().optional(),
  })).optional(),
  planAchievement: z.object({
    targetRevenue: z.number(),
    actualRevenue: z.number(),
    targetOrders: z.number(),
    actualOrders: z.number(),
    achieveRate: z.number(),
  }).nullable().optional(),
  gradeChanges: z.object({
    upgraded: z.number(),
    downgraded: z.number(),
    total: z.number(),
  }).optional(),
  industryBenchmark: z.object({
    avgAdRate: z.number(),
    avgProfitRate: z.number(),
    avgRoas: z.number(),
    avgCtr: z.number(),
    avgCvr: z.number().optional(),
    myAdRate: z.number().optional(),
    myRoas: z.number().optional(),
    myCtr: z.number().optional(),
    adRateVsIndustry: z.string().optional(),
    roasVsIndustry: z.string().optional(),
  }).optional(),
  dataFreshness: z.object({
    lastSync: z.string(),
    attributionWindow: z.string(),
    attributionWindowDays: z.number().optional(),
    confirmedUntil: z.string().optional(),
    note: z.string().optional(),
  }).optional(),
  lastSyncAt: z.union([z.string(), z.date()]).nullable().optional(),
});

// GET /api/dashboard/trend 응답
export const DashboardTrendItemSchema = z.object({
  date: z.string(),
  revenue: z.number(),
  profit: z.number(),
  adCost: z.number(),
});

export type DashboardSummary = z.infer<typeof DashboardSummarySchema>;
export type DashboardTrendItem = z.infer<typeof DashboardTrendItemSchema>;
