/**
 * 마켓플레이스 카탈로그 시드 데이터.
 * MarketplaceService.onModuleInit()에서 호출.
 */

export const WORKFLOW_CATALOG = [
  {
    name: '주문 자동수집',
    description: '셀피아/사방넷에서 오픈마켓+자사몰 주문을 자동 수집하고 송장출력',
    module: 'order',
    category: 'automation',
    icon: '📦',
    nodesJson: [
      { id: 'n1', type: 'trigger', label: '정시 트리거', config: { schedule: '*/30 * * * *' }, position: { x: 100, y: 200 } },
      { id: 'n2', type: 'api_call', label: '셀피아 주문조회', config: { api: 'selpia', endpoint: '/orders' }, position: { x: 350, y: 200 } },
      { id: 'n3', type: 'transform', label: '표준 주문 변환', config: {}, position: { x: 600, y: 200 } },
      { id: 'n4', type: 'db_write', label: 'DB 저장', config: { table: 'orders' }, position: { x: 850, y: 200 } },
    ],
    edgesJson: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
    ],
    configurableParams: [
      { key: 'schedule', nodeId: 'n1', label: '수집 주기', type: 'cron', default: '*/30 * * * *', description: '주문 수집 간격 (cron)' },
    ],
  },
  {
    name: '운송장 자동전송',
    description: '셀피아에서 각 오픈마켓으로 운송장번호 자동전송',
    module: 'order',
    category: 'automation',
    icon: '🚚',
    nodesJson: [
      { id: 'n1', type: 'trigger', label: '출고완료 이벤트', config: { event: 'shipment_complete' }, position: { x: 100, y: 200 } },
      { id: 'n2', type: 'api_call', label: '운송장번호 조회', config: { api: 'selpia' }, position: { x: 350, y: 200 } },
      { id: 'n3', type: 'action', label: '오픈마켓 전송', config: { targets: ['naver', 'coupang', 'gmarket'] }, position: { x: 600, y: 200 } },
    ],
    edgesJson: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
    ],
    configurableParams: [
      { key: 'targets', nodeId: 'n3', label: '전송 대상 마켓', type: 'string', default: 'naver,coupang,gmarket', description: '쉼표로 구분된 마켓 목록' },
    ],
  },
  {
    name: '세금계산서 자동발행',
    description: '무통장입금건 감지 → 홈택스 세금계산서 자동발행',
    module: 'accounting',
    category: 'automation',
    icon: '🧾',
    nodesJson: [
      { id: 'n1', type: 'trigger', label: '입금감지 트리거', config: { event: 'payment_received' }, position: { x: 100, y: 200 } },
      { id: 'n2', type: 'condition', label: '세금계산서 필요?', config: {}, position: { x: 350, y: 200 } },
      { id: 'n3', type: 'api_call', label: '홈택스 발행', config: { api: 'hometax' }, position: { x: 600, y: 100 } },
      { id: 'n4', type: 'notification', label: '발행완료 알림', config: {}, position: { x: 850, y: 200 } },
    ],
    edgesJson: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
    ],
    configurableParams: [
      { key: 'minAmount', label: '최소 금액 (원)', type: 'number', default: 30000, description: '이 금액 이상일 때만 자동발행' },
    ],
  },
  {
    name: '일매출 자동보고서',
    description: '매일 18:00 각 몰 매출 자동집계 → 보고서 생성 → 전달',
    module: 'report',
    category: 'reporting',
    icon: '📊',
    nodesJson: [
      { id: 'n1', type: 'trigger', label: '매일 18:00', config: { schedule: '0 18 * * *' }, position: { x: 100, y: 200 } },
      { id: 'n2', type: 'db_query', label: '몰별 매출 집계', config: {}, position: { x: 350, y: 200 } },
      { id: 'n3', type: 'transform', label: '보고서 생성', config: {}, position: { x: 600, y: 200 } },
      { id: 'n4', type: 'notification', label: '카카오톡 전달', config: { channel: 'kakao' }, position: { x: 850, y: 200 } },
    ],
    edgesJson: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
    ],
    configurableParams: [
      { key: 'schedule', nodeId: 'n1', label: '보고서 생성 시각', type: 'cron', default: '0 18 * * *', description: '매일 보고서를 생성할 시각' },
      { key: 'channel', nodeId: 'n4', label: '알림 채널', type: 'select', default: 'kakao', options: [{ label: '카카오톡', value: 'kakao' }, { label: '슬랙', value: 'slack' }, { label: '이메일', value: 'email' }] },
    ],
  },
  {
    name: '재고 실시간 동기화',
    description: '셀피아 ↔ 심포니 ↔ 사방넷 재고 15분 간격 동기화',
    module: 'inventory',
    category: 'monitoring',
    icon: '🔄',
    nodesJson: [
      { id: 'n1', type: 'trigger', label: '15분 간격', config: { schedule: '*/15 * * * *' }, position: { x: 100, y: 200 } },
      { id: 'n2', type: 'api_call', label: '셀피아 재고 조회', config: { api: 'selpia' }, position: { x: 350, y: 200 } },
      { id: 'n3', type: 'api_call', label: '심포니 재고 조회', config: { api: 'symphony' }, position: { x: 350, y: 350 } },
      { id: 'n4', type: 'transform', label: '차이 비교', config: {}, position: { x: 600, y: 200 } },
      { id: 'n5', type: 'action', label: '동기화 실행', config: {}, position: { x: 850, y: 200 } },
    ],
    edgesJson: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n1', target: 'n3' },
      { id: 'e3', source: 'n2', target: 'n4' },
      { id: 'e4', source: 'n3', target: 'n4' },
      { id: 'e5', source: 'n4', target: 'n5' },
    ],
    configurableParams: [
      { key: 'schedule', nodeId: 'n1', label: '동기화 주기', type: 'cron', default: '*/15 * * * *', description: '재고 동기화 간격' },
      { key: 'threshold', label: '불일치 임계값', type: 'number', default: 5, description: '이 수량 이상 차이 시 알림' },
    ],
  },
  {
    name: 'CS 자동답변',
    description: '오픈마켓 게시판 문의 자동 감지 → AI 답변 생성 → 자동 등록',
    module: 'cs',
    category: 'automation',
    icon: '💬',
    nodesJson: [
      { id: 'n1', type: 'trigger', label: '문의 감지', config: { schedule: '*/10 * * * *' }, position: { x: 100, y: 200 } },
      { id: 'n2', type: 'api_call', label: '미답변 문의 조회', config: {}, position: { x: 350, y: 200 } },
      { id: 'n3', type: 'agent_task', label: 'AI 답변 생성', config: { agentType: 'cs_reply' }, position: { x: 600, y: 200 } },
      { id: 'n4', type: 'action', label: '답변 등록', config: {}, position: { x: 850, y: 200 } },
    ],
    edgesJson: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
    ],
    configurableParams: [
      { key: 'schedule', nodeId: 'n1', label: '문의 감지 주기', type: 'cron', default: '*/10 * * * *', description: '미답변 문의 확인 간격' },
      { key: 'requiresApproval', label: '답변 승인 필요', type: 'boolean', default: true, description: '자동 등록 전 사람 승인 필요 여부' },
    ],
  },
  {
    name: '은행입출금 자동장부',
    description: '오픈뱅킹 API로 입출금 내역 자동 수집 → 엑셀 장부 기재',
    module: 'accounting',
    category: 'automation',
    icon: '🏦',
    nodesJson: [
      { id: 'n1', type: 'trigger', label: '매일 09:00', config: { schedule: '0 9 * * *' }, position: { x: 100, y: 200 } },
      { id: 'n2', type: 'api_call', label: '오픈뱅킹 조회', config: { api: 'open_banking' }, position: { x: 350, y: 200 } },
      { id: 'n3', type: 'transform', label: '분류/매칭', config: {}, position: { x: 600, y: 200 } },
      { id: 'n4', type: 'action', label: '장부 기재', config: {}, position: { x: 850, y: 200 } },
    ],
    edgesJson: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
    ],
    configurableParams: [
      { key: 'schedule', nodeId: 'n1', label: '수집 시각', type: 'cron', default: '0 9 * * *', description: '입출금 내역 수집 시각' },
    ],
  },
];

export const AGENT_CATALOG = [
  {
    name: '광고 전략 에이전트',
    description: '쿠팡 광고 ROAS/CTR 분석 후 예산 조정 판단. 재고 0 상품 즉시 중단.',
    role: 'specialist',
    category: 'operations',
    icon: '📢',
    adapterType: 'claude_local',
    promptTemplate: '광고 전략 에이전트 프롬프트 (설치 시 seed-agents.ts 원본 사용)',
    skills: ['db-query', 'result-callback'],
    permissions: { canAccessBrowser: false, canModifyData: false },
    configurableParams: [
      { key: 'schedule', label: '실행 스케줄', type: 'cron', default: '0 9 * * *', description: '광고 분석 실행 시각' },
      { key: 'monthlyTokenBudget', label: '월 토큰 예산', type: 'number', default: 500000, description: '월간 최대 토큰 사용량' },
      { key: 'requiresApproval', label: '실행 전 승인', type: 'boolean', default: true, description: '광고 조정 실행 전 사람 승인 필요' },
      { key: 'dailyBudgetLimit', label: '일일 광고비 상한 (원)', type: 'number', default: 100000 },
    ],
  },
  {
    name: '건강도 평가 에이전트',
    description: '43개 규칙 기반 상품 건강도 점수 산출. 위반사항 자동 감지.',
    role: 'specialist',
    category: 'analytics',
    icon: '🏥',
    adapterType: 'claude_local',
    promptTemplate: '건강도 평가 에이전트 프롬프트 (설치 시 seed-agents.ts 원본 사용)',
    skills: ['db-query', 'result-callback'],
    permissions: { canAccessBrowser: false, canModifyData: false },
    configurableParams: [
      { key: 'schedule', label: '평가 스케줄', type: 'cron', default: '0 6 * * *', description: '건강도 평가 실행 시각' },
      { key: 'monthlyTokenBudget', label: '월 토큰 예산', type: 'number', default: 300000 },
      { key: 'requiresApproval', label: '실행 전 승인', type: 'boolean', default: false },
    ],
  },
  {
    name: '규칙 임계값 추천 에이전트',
    description: '상품 데이터 분포 분석으로 규칙 임계값 자동 추천.',
    role: 'specialist',
    category: 'analytics',
    icon: '📐',
    adapterType: 'claude_local',
    promptTemplate: '규칙 임계값 추천 에이전트 프롬프트 (설치 시 seed-agents.ts 원본 사용)',
    skills: ['db-query', 'result-callback'],
    permissions: { canAccessBrowser: false, canModifyData: false },
    configurableParams: [
      { key: 'monthlyTokenBudget', label: '월 토큰 예산', type: 'number', default: 100000 },
      { key: 'requiresApproval', label: '실행 전 승인', type: 'boolean', default: false },
    ],
  },
  {
    name: '운영 매니저',
    description: '셀러 운영 총괄. 자유 질문 답변 및 specialist 에이전트 위임.',
    role: 'manager',
    category: 'operations',
    icon: '👔',
    adapterType: 'claude_local',
    promptTemplate: '운영 매니저 프롬프트 (설치 시 seed-agents.ts 원본 사용)',
    skills: ['db-query', 'kiditem-api', 'data-analysis', 'result-callback'],
    permissions: { canSpawnSubAgents: true, canAccessBrowser: false, canModifyData: false },
    configurableParams: [
      { key: 'monthlyTokenBudget', label: '월 토큰 예산', type: 'number', default: 1000000 },
      { key: 'requiresApproval', label: '실행 전 승인', type: 'boolean', default: false },
    ],
  },
  {
    name: '가격 조정 에이전트',
    description: '마진율/경쟁사 가격/광고 효율 기반 가격 조정 추천.',
    role: 'specialist',
    category: 'operations',
    icon: '💰',
    adapterType: 'claude_local',
    promptTemplate: '가격 조정 에이전트 프롬프트 (설치 시 seed-agents.ts 원본 사용)',
    skills: ['db-query', 'result-callback'],
    permissions: { canAccessBrowser: false, canModifyData: false },
    configurableParams: [
      { key: 'schedule', label: '실행 스케줄', type: 'cron', default: '0 10 * * *', description: '가격 분석 실행 시각' },
      { key: 'monthlyTokenBudget', label: '월 토큰 예산', type: 'number', default: 300000 },
      { key: 'requiresApproval', label: '가격 변경 전 승인', type: 'boolean', default: true },
    ],
  },
  {
    name: '재고 알림 에이전트',
    description: '재고 부족/과잉 감지 및 발주 추천.',
    role: 'specialist',
    category: 'monitoring',
    icon: '📦',
    adapterType: 'claude_local',
    promptTemplate: '재고 알림 에이전트 프롬프트 (설치 시 seed-agents.ts 원본 사용)',
    skills: ['db-query', 'result-callback'],
    permissions: { canAccessBrowser: false, canModifyData: false },
    configurableParams: [
      { key: 'schedule', label: '점검 스케줄', type: 'cron', default: '0 */6 * * *', description: '재고 점검 간격' },
      { key: 'monthlyTokenBudget', label: '월 토큰 예산', type: 'number', default: 200000 },
      { key: 'requiresApproval', label: '실행 전 승인', type: 'boolean', default: false },
      { key: 'thresholdDays', label: '부족 기준 (일)', type: 'number', default: 7, description: '이 일수 이하 재고 시 알림' },
    ],
  },
  {
    name: '리뷰 모니터링 에이전트',
    description: '리뷰 분석 및 품질 이슈 조기 감지.',
    role: 'specialist',
    category: 'monitoring',
    icon: '⭐',
    adapterType: 'claude_local',
    promptTemplate: '리뷰 모니터링 에이전트 프롬프트 (설치 시 seed-agents.ts 원본 사용)',
    skills: ['db-query', 'result-callback'],
    permissions: { canAccessBrowser: false, canModifyData: false },
    configurableParams: [
      { key: 'schedule', label: '점검 스케줄', type: 'cron', default: '0 9 * * *', description: '리뷰 분석 실행 시각' },
      { key: 'monthlyTokenBudget', label: '월 토큰 예산', type: 'number', default: 200000 },
      { key: 'requiresApproval', label: '실행 전 승인', type: 'boolean', default: false },
    ],
  },
];
