import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/schemas/index.ts',
    'src/product/index.ts',
    'src/product-content/index.ts',
    'src/sourcing/index.ts',
    'src/channel-listing.ts',
    'src/order.ts',
    'src/inventory.ts',
    'src/ai.ts',
    'src/advertising.ts',
    'src/errors/index.ts',
    'src/server-errors.ts',
    'src/security/index.ts',
    'src/dashboard.ts',
    'src/finance.ts',
    'src/supplier-stats.ts',
    'src/channel-dashboard.ts',
    'src/channel-account.ts',
    'src/coupang-direct-order.ts',
    'src/channel-sku-matching.ts',
    'src/channel-sku-availability.ts',
    'src/mall-publishing.ts',
    'src/mall-operation-outcomes.ts',
    'src/inventory-availability.ts',
    'src/channel-option-capacity.ts',
    'src/product-operations.ts',
    'src/product-abc.ts',
    'src/channel-product-matching.ts',
    'src/source-import.ts',
    'src/sellpia-inventory-freshness.ts',
    'src/sellpia-order-transmission.ts',
    'src/sellpia-manual-match.ts',
    'src/rocket-purchase-preview.ts',
    'src/sabangnet-mall-listings.ts',
    'src/coupang-catalog-snapshot.ts',
    'src/identifiers/index.ts',
    'src/agent-interaction/index.ts',
    'src/agent-runtime/index.ts',
    'src/common.ts',
    'src/reviews.ts',
    'src/statistics.ts',
    'src/settlements.ts',
    'src/alerts.ts',
    'src/feature-gate.ts',
    'src/inspection.ts',
    'src/readiness.ts',
    'src/coupang-category.ts',
    'src/auth.ts',
    'src/operation-cancellation.ts',
    'src/operations.ts',
    'src/browser-collection-session.ts',
    'src/collection-start.ts',
    'src/order-collection-source.ts',
    'src/source-readiness.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  outDir: 'dist',
});
