import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/schemas/index.ts',
    'src/product/index.ts',
    'src/product-content/index.ts',
    'src/order.ts',
    'src/inventory.ts',
    'src/ai.ts',
    'src/advertising.ts',
    'src/errors/index.ts',
    'src/server-errors.ts',
    'src/security/index.ts',
    'src/panel/index.ts',
    'src/dashboard.ts',
    'src/finance.ts',
    'src/marketplace.ts',
    'src/rules.ts',
    'src/action-task.ts',
    'src/supplier-stats.ts',
    'src/channel-dashboard.ts',
    'src/channel-account.ts',
    'src/channel-sku-matching.ts',
    'src/channel-sku-availability.ts',
    'src/source-import.ts',
    'src/agent-os.ts',
    'src/workflow.ts',
    'src/common.ts',
    'src/reviews.ts',
    'src/statistics.ts',
    'src/settlements.ts',
    'src/alerts.ts',
    'src/return-summary.ts',
    'src/feature-gate.ts',
    'src/inspection.ts',
    'src/readiness.ts',
    'src/auth.ts',
    'src/operation-cancellation.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  outDir: 'dist',
});
