import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/schemas/index.ts',
    'src/product/index.ts',
    'src/product-content/index.ts',
    'src/sourcing/index.ts',
    'src/product-preparation-payload.ts',
    'src/channel-listing.ts',
    'src/order.ts',
    'src/inventory.ts',
    'src/ai.ts',
    'src/advertising.ts',
    'src/errors/index.ts',
    'src/server-errors.ts',
    'src/security/index.ts',
    'src/panel/index.ts',
    'src/dashboard.ts',
    'src/finance.ts',
    'src/marketplace.ts',
    'src/rules.ts',
    'src/action-task.ts',
    'src/supplier-stats.ts',
    'src/channel-dashboard.ts',
    'src/channel-account.ts',
    'src/coupang-direct-order.ts',
    'src/channel-sku-matching.ts',
    'src/channel-sku-availability.ts',
    'src/inventory-commitment.ts',
    'src/product-operations.ts',
    'src/channel-product-matching.ts',
    'src/channel-recipe-automation.ts',
    'src/source-import.ts',
    'src/sellpia-inventory-freshness.ts',
    'src/rocket-purchase-preview.ts',
    'src/coupang-catalog-snapshot.ts',
    'src/agent-os.ts',
    'src/workflow.ts',
    'src/common.ts',
    'src/reviews.ts',
    'src/statistics.ts',
    'src/settlements.ts',
    'src/alerts.ts',
    'src/return-summary.ts',
    'src/feature-gate.ts',
    'src/inspection.ts',
    'src/readiness.ts',
    'src/coupang-category.ts',
    'src/auth.ts',
    'src/operation-cancellation.ts',
    'src/browser-collection-session.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  outDir: 'dist',
});
