import { describe, expect, it } from 'vitest';
import { buildAgentOfficeModel } from './agent-office-model';

describe('buildAgentOfficeModel', () => {
  it('derives office node statuses from runs, requests, and approvals', () => {
    const model = buildAgentOfficeModel({
      instances: [
        {
          id: 'agent-manager',
          organizationId: 'org-1',
          type: 'manager',
          name: 'Operator',
          role: 'orchestrator',
          title: '대표실',
          icon: null,
          reportsToId: null,
          lifecycleStatus: 'active',
          pauseReason: null,
          trustLevel: 1,
          adapterType: 'hermes_local',
          modelOverride: null,
          effectiveModel: 'gpt-5.1-codex',
        },
        {
          id: 'agent-sourcing',
          organizationId: 'org-1',
          type: 'sourcing',
          name: 'Sourcing Agent',
          role: 'specialist',
          title: '소싱 데스크',
          icon: null,
          reportsToId: 'agent-manager',
          lifecycleStatus: 'active',
          pauseReason: null,
          trustLevel: 0,
          adapterType: 'hermes_local',
          modelOverride: null,
          effectiveModel: 'gpt-5.1-codex',
        },
      ],
      runs: [
        {
          id: 'run-1',
          organizationId: 'org-1',
          agentInstanceId: 'agent-manager',
          requestId: 'request-1',
          taskKey: 'conversation:conversation-1',
          status: 'running',
          attempt: 1,
          invocationSource: 'agent_os_conversation',
          adapterType: 'hermes_local',
          model: 'gpt-5.1-codex',
          provider: 'hermes',
          startedAt: '2026-07-09T00:00:00.000Z',
          finishedAt: null,
          errorCode: null,
          errorMessage: null,
          output: null,
          costMicros: null,
        },
      ],
      requests: [
        {
          id: 'request-2',
          organizationId: 'org-1',
          agentInstanceId: 'agent-sourcing',
          agentType: 'sourcing',
          taskKey: 'conversation:conversation-1:sourcing',
          source: 'agent_os_conversation',
          sourceResourceType: null,
          sourceResourceId: null,
          sourceWorkflowRunId: null,
          status: 'requires_approval',
          priority: 5,
          attempts: 0,
          maxAttempts: 1,
          scheduledFor: '2026-07-09T00:01:00.000Z',
          claimedAt: null,
          finishedAt: null,
          latestRunId: null,
          lastErrorCode: null,
          lastErrorMessage: null,
          createdAt: '2026-07-09T00:01:00.000Z',
        },
      ],
      approvals: [
        {
          id: 'approval-1',
          organizationId: 'org-1',
          agentInstanceId: 'agent-sourcing',
          requestId: 'request-2',
          runId: null,
          status: 'pending',
          reasonCode: 'approval_required',
          reason: '발주 전 확인',
          prompt: null,
          payload: {},
          actionSnapshot: null,
          requestedByActorType: 'agent',
          requestedByActorId: 'agent-sourcing',
          requestedByUserId: null,
          approverUserId: null,
          decidedByUserId: null,
          decidedAt: null,
          decisionReason: null,
          expiresAt: null,
          createdAt: '2026-07-09T00:02:00.000Z',
          updatedAt: '2026-07-09T00:02:00.000Z',
        },
      ],
      conversations: [],
      costEvents: [],
      authorizationEvents: [],
      totalCostMicros: '0',
    });

    expect(model.nodes.map((node) => [node.id, node.status])).toEqual([
      ['agent-manager', 'working'],
      ['agent-sourcing', 'blocked'],
    ]);
    expect(model.totals).toMatchObject({
      agents: 2,
      working: 1,
      blocked: 1,
      pendingApprovals: 1,
      runningRuns: 1,
      totalCostMicros: '0',
    });
  });

  it('sorts activities with newest first', () => {
    const model = buildAgentOfficeModel({
      instances: [],
      runs: [],
      requests: [],
      approvals: [],
      conversations: [
        {
          id: 'conversation-1',
          organizationId: 'org-1',
          title: '첫 대화',
          status: 'active',
          createdByUserId: 'user-1',
          rootRequestId: null,
          lastMessageAt: '2026-07-09T00:05:00.000Z',
          createdAt: '2026-07-09T00:00:00.000Z',
          updatedAt: '2026-07-09T00:05:00.000Z',
        },
      ],
      costEvents: [
        {
          id: 'cost-1',
          organizationId: 'org-1',
          agentInstanceId: 'agent-manager',
          requestId: 'request-1',
          runId: 'run-1',
          provider: 'hermes',
          model: 'gpt-5.1-codex',
          inputTokens: 10,
          outputTokens: 4,
          cachedInputTokens: 2,
          costMicros: '1000',
          occurredAt: '2026-07-09T00:03:00.000Z',
        },
      ],
      authorizationEvents: [],
      totalCostMicros: '1000',
    });

    expect(model.activities.map((activity) => activity.id)).toEqual([
      'conversation-1',
      'cost-1',
    ]);
  });

  it('treats claimed requests as active work before a run starts', () => {
    const model = buildAgentOfficeModel({
      instances: [
        {
          id: 'agent-review',
          organizationId: 'org-1',
          type: 'review',
          name: 'Review Agent',
          role: 'specialist',
          title: '검토 데스크',
          icon: null,
          reportsToId: null,
          lifecycleStatus: 'active',
          pauseReason: null,
          trustLevel: 1,
          adapterType: 'hermes_local',
          modelOverride: null,
          effectiveModel: 'gpt-5.1-codex',
        },
      ],
      runs: [],
      requests: [
        {
          id: 'request-claimed',
          organizationId: 'org-1',
          agentInstanceId: 'agent-review',
          agentType: 'review',
          taskKey: 'conversation:conversation-2:review',
          source: 'agent_os_conversation',
          sourceResourceType: null,
          sourceResourceId: null,
          sourceWorkflowRunId: null,
          status: 'claimed',
          priority: 3,
          attempts: 0,
          maxAttempts: 1,
          scheduledFor: '2026-07-09T01:00:00.000Z',
          claimedAt: '2026-07-09T01:01:00.000Z',
          finishedAt: null,
          latestRunId: null,
          lastErrorCode: null,
          lastErrorMessage: null,
          createdAt: '2026-07-09T01:00:00.000Z',
        },
        {
          id: 'request-pending',
          organizationId: 'org-1',
          agentInstanceId: 'agent-review',
          agentType: 'review',
          taskKey: 'conversation:conversation-2:followup',
          source: 'agent_os_conversation',
          sourceResourceType: null,
          sourceResourceId: null,
          sourceWorkflowRunId: null,
          status: 'pending',
          priority: 2,
          attempts: 0,
          maxAttempts: 1,
          scheduledFor: '2026-07-09T01:02:00.000Z',
          claimedAt: null,
          finishedAt: null,
          latestRunId: null,
          lastErrorCode: null,
          lastErrorMessage: null,
          createdAt: '2026-07-09T01:02:00.000Z',
        },
      ],
      approvals: [],
      conversations: [],
      costEvents: [],
      authorizationEvents: [],
      totalCostMicros: '0',
    });

    expect(model.nodes).toMatchObject([
      {
        id: 'agent-review',
        status: 'working',
        activeRunCount: 1,
      },
    ]);
    expect(model.totals).toMatchObject({
      working: 1,
      waiting: 0,
      runningRuns: 0,
    });
  });
});
