import {
  defineRequiredColumnCleanups,
  removeRowsBlockingRequiredColumns,
} from '../helpers/required-column-row-cleanup';
import type { DataMigration } from '../types';

const UNLINKED_SOURCING_SNAPSHOT =
  'PR #493 made ingestion_run_id a required foreign key to '
  + 'sourcing_evidence_ingestion_runs. A row written before that names no '
  + 'ingestion run, and the sources collect again as attempts.';

/**
 * KID-239: the tables whose Office 0.1.30 rows cannot hold a column v0.1.31
 * makes required. The owner decided on 2026-09-17 to delete these rows instead
 * of backfilling them, signal alerts included (ADR-0010). No foreign key
 * references any of them, in the Office 0.1.30 schema or in v0.1.31. Restated
 * because a migration records one moment.
 */
export const REQUIRED_COLUMN_CLEANUPS = defineRequiredColumnCleanups([
  {
    table: 'naver_keyword_daily_snapshots',
    requiredColumn: 'ingestion_run_id',
    reason: UNLINKED_SOURCING_SNAPSHOT,
  },
  {
    table: 'naver_popular_keyword_daily_snapshots',
    requiredColumn: 'ingestion_run_id',
    reason: UNLINKED_SOURCING_SNAPSHOT,
  },
  {
    table: 'shorts_trend_daily_snapshots',
    requiredColumn: 'ingestion_run_id',
    reason: UNLINKED_SOURCING_SNAPSHOT,
  },
  {
    table: 'live_commerce_broadcast_daily_snapshots',
    requiredColumn: 'ingestion_run_id',
    reason: UNLINKED_SOURCING_SNAPSHOT,
  },
  {
    table: 'live_commerce_product_daily_snapshots',
    requiredColumn: 'ingestion_run_id',
    reason: UNLINKED_SOURCING_SNAPSHOT,
  },
  {
    table: 'tiktok_creative_trend_daily_snapshots',
    requiredColumn: 'ingestion_run_id',
    reason: UNLINKED_SOURCING_SNAPSHOT,
  },
  {
    table: 'alerts',
    requiredColumn: 'dedupe_key',
    reason:
      'The alert contract made dedupe_key required, and its @default(uuid()) '
      + 'is generated by the Prisma client, so the database cannot fill existing '
      + 'rows. v0.1.31:005 keeps signal alerts, which Office 0.1.30 writes, and '
      + 'ADR-0010 does not keep alerts.',
  },
]);

/**
 * Pre-schema and registered right after 013, so 005 and 008 have already
 * recorded their alert work when this deletes the alerts that remain. The
 * Office deployer's cutover survey runs after the pre-schema phase and stops
 * before `db push` if a row still blocks it.
 */
export const removeRowsBlockingRequiredColumnsMigration: DataMigration = {
  id: 'v0.1.31:014_remove_rows_blocking_required_columns',
  releaseVersion: '0.1.31',
  name: 'Remove rows that cannot hold a column the schema makes required before db push',
  phase: 'pre-schema',
  run: (tx) => removeRowsBlockingRequiredColumns(tx, REQUIRED_COLUMN_CLEANUPS),
};
