export const INTERACTION_CLOCK = Symbol("INTERACTION_CLOCK");
export const INTERACTION_GATEWAY_SHARED_SECRET = Symbol(
  "INTERACTION_GATEWAY_SHARED_SECRET",
);
export const INTERACTION_PRINCIPAL_HMAC_KEY = Symbol(
  "INTERACTION_PRINCIPAL_HMAC_KEY",
);
export const INTERACTION_RUN_INTENT_HMAC_KEY = Symbol(
  "INTERACTION_RUN_INTENT_HMAC_KEY",
);
export const INTERACTION_REPLAY_CURSOR_HMAC_KEY = Symbol(
  "INTERACTION_REPLAY_CURSOR_HMAC_KEY",
);
export type InteractionClock = () => Date;
