interface SeedRule {
  name: string;
  displayName: string;
  description: string;
  category: string;
  severity: string;
  field: string;
  operator: string;
  threshold: Record<string, number>;
  messageTemplate: string;
  actionType: string | null;
  autoExecute: boolean;
  sortOrder: number;
}

export const SEED_RULES: SeedRule[] = [
  // ─── Profitability (8 rules) ─────────────────────────────────────────────────
  {
    name: 'deficit-detection',
    displayName: '적자 상품 감지',
    description: '순이익률이 0% 미만인 상품 감지',
    category: 'profitability',
    severity: 'critical',
    field: 'profitRate',
    operator: 'lt',
    threshold: { value: 0 },
    messageTemplate: '순이익률 {{value}}% — 즉시 아웃 검토 필요',
    actionType: 'product.review_pricing',
    autoExecute: false,
    sortOrder: 1,
  },
  {
    name: 'low-profit-detection',
    displayName: '저이익 상품 감지',
    description: '순이익률 0~3% 사이 상품 감지',
    category: 'profitability',
    severity: 'warning',
    field: 'profitRate',
    operator: 'lte',
    threshold: { value: 3 },
    messageTemplate: '순이익률 {{value}}% — 개선 또는 정리 판단 필요',
    actionType: 'product.review_pricing',
    autoExecute: false,
    sortOrder: 2,
  },
  {
    name: 'low-margin',
    displayName: '마진율 부족',
    description: '마진율 30% 미만',
    category: 'profitability',
    severity: 'warning',
    field: 'margin',
    operator: 'lt',
    threshold: { value: 30 },
    messageTemplate: '마진율 {{value}}% — 30% 미만',
    actionType: 'product.review_pricing',
    autoExecute: false,
    sortOrder: 3,
  },
  {
    name: 'high-cost-rate',
    displayName: '원가율 과다',
    description: '원가율 70% 이상',
    category: 'profitability',
    severity: 'warning',
    field: 'costRate',
    operator: 'gte',
    threshold: { value: 70 },
    messageTemplate: '원가율 {{value}}% — 소싱처 변경 검토',
    actionType: 'product.review_pricing',
    autoExecute: false,
    sortOrder: 4,
  },
  {
    name: 'no-revenue',
    displayName: '매출 없음',
    description: '매출 0원 상품',
    category: 'profitability',
    severity: 'warning',
    field: 'revenue',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: '매출 없음 — 노출/광고 상태 확인 필요',
    actionType: 'product.check_listing',
    autoExecute: false,
    sortOrder: 5,
  },
  {
    name: 'high-net-loss',
    displayName: '순손실 과다',
    description: '순손실 -50000원 이하',
    category: 'profitability',
    severity: 'critical',
    field: 'netProfit',
    operator: 'lt',
    threshold: { value: -50000 },
    messageTemplate: '순손실 {{value}}원 — 긴급 검토 필요',
    actionType: 'product.stop_sales',
    autoExecute: false,
    sortOrder: 6,
  },
  {
    name: 'cost-exceeds-price',
    displayName: '원가 > 판매가',
    description: '원가가 판매가보다 높은 상품',
    category: 'profitability',
    severity: 'critical',
    field: 'margin',
    operator: 'lt',
    threshold: { value: 0 },
    messageTemplate: '원가가 판매가보다 높음 — 즉시 가격 조정 필요',
    actionType: 'product.review_pricing',
    autoExecute: false,
    sortOrder: 7,
  },
  {
    name: 'breakeven-risk',
    displayName: '손익분기 위험',
    description: '순이익률 0~1% — 손익분기점 근접',
    category: 'profitability',
    severity: 'info',
    field: 'profitRate',
    operator: 'lte',
    threshold: { value: 1 },
    messageTemplate: '순이익률 {{value}}% — 손익분기점 근접',
    actionType: null,
    autoExecute: false,
    sortOrder: 8,
  },

  // ─── Advertising (10 rules) ──────────────────────────────────────────────────
  {
    name: 'ad-rate-exceeded',
    displayName: '광고비율 초과',
    description: '광고비율 15% 초과',
    category: 'advertising',
    severity: 'warning',
    field: 'adRate',
    operator: 'gt',
    threshold: { value: 15 },
    messageTemplate: '광고비율 {{value}}% — 15% 초과',
    actionType: 'product.reduce_ad_bid',
    autoExecute: false,
    sortOrder: 10,
  },
  {
    name: 'ad-rate-critical',
    displayName: '광고비율 위험',
    description: '광고비율 25% 초과',
    category: 'advertising',
    severity: 'critical',
    field: 'adRate',
    operator: 'gt',
    threshold: { value: 25 },
    messageTemplate: '광고비율 {{value}}% — 즉시 광고 중단 검토',
    actionType: 'product.stop_ads',
    autoExecute: false,
    sortOrder: 11,
  },
  {
    name: 'a-grade-no-ad',
    displayName: 'A등급 광고 미배정',
    description: 'A등급이지만 광고 미배정',
    category: 'advertising',
    severity: 'info',
    field: 'adCostRate',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: 'A등급이지만 광고 미배정 — 광고 배정 검토',
    actionType: 'product.assign_ad',
    autoExecute: false,
    sortOrder: 12,
  },
  {
    name: 'c-grade-high-ad',
    displayName: 'C등급 광고 과다',
    description: 'C등급에 광고비 5% 이상',
    category: 'advertising',
    severity: 'warning',
    field: 'adRate',
    operator: 'gt',
    threshold: { value: 5 },
    messageTemplate: 'C등급 상품에 광고비 {{value}}% — 광고 축소 검토',
    actionType: 'product.reduce_ad_bid',
    autoExecute: false,
    sortOrder: 13,
  },
  {
    name: 'deficit-with-ad',
    displayName: '적자+광고 집행',
    description: '적자 상품에 광고 집행 중',
    category: 'advertising',
    severity: 'critical',
    field: 'adCostRate',
    operator: 'gt',
    threshold: { value: 0 },
    messageTemplate: '적자 상품에 광고비 {{value}}% 집행 중 — 즉시 중단',
    actionType: 'product.stop_ads',
    autoExecute: false,
    sortOrder: 14,
  },
  {
    name: 'ad-spend-no-revenue',
    displayName: '광고비만 소진',
    description: '광고비 지출 중이나 매출 없음',
    category: 'advertising',
    severity: 'warning',
    field: 'adRate',
    operator: 'gt',
    threshold: { value: 100 },
    messageTemplate: '광고비만 소진, 매출 없음 — 광고 효율 점검',
    actionType: 'product.stop_ads',
    autoExecute: false,
    sortOrder: 15,
  },
  {
    name: 'low-roas',
    displayName: 'ROAS 저조',
    description: '광고비율 대비 매출 비효율',
    category: 'advertising',
    severity: 'warning',
    field: 'adRate',
    operator: 'gt',
    threshold: { value: 20 },
    messageTemplate: '광고비율 {{value}}% — ROAS 저조, 키워드/입찰가 조정',
    actionType: 'product.reduce_ad_bid',
    autoExecute: false,
    sortOrder: 16,
  },
  {
    name: 'b-grade-no-ad',
    displayName: 'B등급 광고 미배정',
    description: 'B등급이지만 광고 없음',
    category: 'advertising',
    severity: 'info',
    field: 'adCostRate',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: 'B등급 광고 미배정 — 2차 광고 배정 검토',
    actionType: 'product.assign_ad',
    autoExecute: false,
    sortOrder: 17,
  },
  {
    name: 'ad-budget-exceeded',
    displayName: '광고 예산 초과',
    description: '월 광고비가 매출의 30% 초과',
    category: 'advertising',
    severity: 'critical',
    field: 'adRate',
    operator: 'gt',
    threshold: { value: 30 },
    messageTemplate: '광고비 {{value}}% — 예산 한도 초과, 즉시 조정',
    actionType: 'product.stop_ads',
    autoExecute: false,
    sortOrder: 18,
  },
  {
    name: 'ad-efficiency-check',
    displayName: '광고 효율 점검',
    description: '광고비율 10~15% 구간 — 모니터링',
    category: 'advertising',
    severity: 'info',
    field: 'adRate',
    operator: 'gt',
    threshold: { value: 10 },
    messageTemplate: '광고비율 {{value}}% — 효율 모니터링 필요',
    actionType: null,
    autoExecute: false,
    sortOrder: 19,
  },

  // ─── Inventory (8 rules) ─────────────────────────────────────────────────────
  {
    name: 'out-of-stock',
    displayName: '품절',
    description: '재고 0 — 품절 상태',
    category: 'inventory',
    severity: 'critical',
    field: 'currentStock',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: '재고 0 — 품절 상태. 긴급 발주 필요',
    actionType: 'product.create_purchase_order',
    autoExecute: false,
    sortOrder: 20,
  },
  {
    name: 'low-stock',
    displayName: '재고 부족',
    description: '재고가 발주점 이하',
    category: 'inventory',
    severity: 'warning',
    field: 'currentStock',
    operator: 'lte',
    threshold: { value: 10 },
    messageTemplate: '재고 {{value}}개 — 발주점 이하, 발주 추천',
    actionType: 'product.create_purchase_order',
    autoExecute: false,
    sortOrder: 21,
  },
  {
    name: 'stock-exhaustion-7d',
    displayName: '7일 내 품절 예상',
    description: '현재 판매속도 기준 7일 내 품절',
    category: 'inventory',
    severity: 'critical',
    field: 'daysOfStock',
    operator: 'lt',
    threshold: { value: 7 },
    messageTemplate: '{{value}}일 후 품절 예상 — 긴급 발주 필요',
    actionType: 'product.create_purchase_order',
    autoExecute: false,
    sortOrder: 22,
  },
  {
    name: 'stock-exhaustion-14d',
    displayName: '14일 내 품절 예상',
    description: '현재 판매속도 기준 14일 내 품절',
    category: 'inventory',
    severity: 'warning',
    field: 'daysOfStock',
    operator: 'lt',
    threshold: { value: 14 },
    messageTemplate: '{{value}}일 후 품절 예상 — 발주 계획 수립',
    actionType: 'product.create_purchase_order',
    autoExecute: false,
    sortOrder: 23,
  },
  {
    name: 'overstock-90d',
    displayName: '과재고 (90일+)',
    description: '현재 재고로 90일 이상 판매 가능',
    category: 'inventory',
    severity: 'info',
    field: 'daysOfStock',
    operator: 'gt',
    threshold: { value: 90 },
    messageTemplate: '재고 {{value}}일분 — 과재고, 프로모션 검토',
    actionType: 'product.create_promotion',
    autoExecute: false,
    sortOrder: 24,
  },
  {
    name: 'overstock-180d',
    displayName: '장기 과재고 (180일+)',
    description: '현재 재고로 180일 이상 — 정리 대상',
    category: 'inventory',
    severity: 'warning',
    field: 'daysOfStock',
    operator: 'gt',
    threshold: { value: 180 },
    messageTemplate: '재고 {{value}}일분 — 장기 과재고, 할인/번들 판매 검토',
    actionType: 'product.create_promotion',
    autoExecute: false,
    sortOrder: 25,
  },
  {
    name: 'no-sales-with-stock',
    displayName: '재고 있으나 판매 없음',
    description: '재고는 있지만 일평균 판매 0',
    category: 'inventory',
    severity: 'warning',
    field: 'avgDailySales',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: '재고 보유 중이나 판매 없음 — 리스팅 확인',
    actionType: 'product.check_listing',
    autoExecute: false,
    sortOrder: 26,
  },
  {
    name: 'safety-stock-breach',
    displayName: '안전재고 미달',
    description: '재고가 안전재고 수준 미달',
    category: 'inventory',
    severity: 'warning',
    field: 'currentStock',
    operator: 'lte',
    threshold: { value: 5 },
    messageTemplate: '재고 {{value}}개 — 안전재고 미달',
    actionType: 'product.create_purchase_order',
    autoExecute: false,
    sortOrder: 27,
  },

  // ─── Feedback (8 rules) ──────────────────────────────────────────────────────
  {
    name: 'no-reviews',
    displayName: '리뷰 없음',
    description: '리뷰 0개 상품',
    category: 'feedback',
    severity: 'info',
    field: 'reviewCount',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: '리뷰 없음 — 리뷰 확보 캠페인 필요',
    actionType: 'product.request_review',
    autoExecute: false,
    sortOrder: 30,
  },
  {
    name: 'low-reviews-a-grade',
    displayName: 'A등급 리뷰 부족',
    description: 'A등급이지만 리뷰 10개 미만',
    category: 'feedback',
    severity: 'warning',
    field: 'reviewCount',
    operator: 'lt',
    threshold: { value: 10 },
    messageTemplate: 'A등급이지만 리뷰 {{value}}개 — 리뷰 확보 시급',
    actionType: 'product.request_review',
    autoExecute: false,
    sortOrder: 31,
  },
  {
    name: 'low-reviews-general',
    displayName: '리뷰 부족',
    description: '리뷰 5개 미만',
    category: 'feedback',
    severity: 'info',
    field: 'reviewCount',
    operator: 'lt',
    threshold: { value: 5 },
    messageTemplate: '리뷰 {{value}}개 — 5개 미만, 확보 검토',
    actionType: 'product.request_review',
    autoExecute: false,
    sortOrder: 32,
  },
  {
    name: 'low-ctr',
    displayName: '클릭률 저조',
    description: 'CTR 1.5% 미만',
    category: 'feedback',
    severity: 'warning',
    field: 'thumbnailCTR',
    operator: 'lt',
    threshold: { value: 1.5 },
    messageTemplate: 'CTR {{value}}% — 1.5% 미만, 썸네일 교체 검토',
    actionType: 'product.change_thumbnail',
    autoExecute: false,
    sortOrder: 33,
  },
  {
    name: 'very-low-ctr',
    displayName: '클릭률 위험',
    description: 'CTR 0.5% 미만',
    category: 'feedback',
    severity: 'critical',
    field: 'thumbnailCTR',
    operator: 'lt',
    threshold: { value: 0.5 },
    messageTemplate: 'CTR {{value}}% — 0.5% 미만, 즉시 썸네일 교체',
    actionType: 'product.change_thumbnail',
    autoExecute: false,
    sortOrder: 34,
  },
  {
    name: 'high-ctr-opportunity',
    displayName: '고CTR 상품 기회',
    description: 'CTR 5% 이상 — 전환 최적화 기회',
    category: 'feedback',
    severity: 'info',
    field: 'thumbnailCTR',
    operator: 'gt',
    threshold: { value: 5 },
    messageTemplate: 'CTR {{value}}% — 높은 클릭률, 전환 최적화 기회',
    actionType: null,
    autoExecute: false,
    sortOrder: 35,
  },
  {
    name: 'review-growth-needed',
    displayName: '리뷰 성장 필요',
    description: '리뷰 20개 미만 + 매출 있는 상품',
    category: 'feedback',
    severity: 'info',
    field: 'reviewCount',
    operator: 'lt',
    threshold: { value: 20 },
    messageTemplate: '리뷰 {{value}}개 — 매출 대비 리뷰 부족',
    actionType: 'product.request_review',
    autoExecute: false,
    sortOrder: 36,
  },
  {
    name: 'ctr-monitoring',
    displayName: 'CTR 모니터링',
    description: 'CTR 1.5~2.5% — 개선 여지',
    category: 'feedback',
    severity: 'info',
    field: 'thumbnailCTR',
    operator: 'lt',
    threshold: { value: 2.5 },
    messageTemplate: 'CTR {{value}}% — 개선 여지 있음',
    actionType: null,
    autoExecute: false,
    sortOrder: 37,
  },

  // ─── Order (9 rules) ─────────────────────────────────────────────────────────
  {
    name: 'high-volume-product',
    displayName: '대량 주문 상품',
    description: '월 주문 50건 이상',
    category: 'order',
    severity: 'info',
    field: 'orderCount',
    operator: 'gte',
    threshold: { value: 50 },
    messageTemplate: '주문 {{value}}건 — 핵심 상품 관리 강화 필요',
    actionType: 'product.upgrade_grade',
    autoExecute: false,
    sortOrder: 40,
  },
  {
    name: 'no-orders',
    displayName: '주문 없음',
    description: '월 주문 0건',
    category: 'order',
    severity: 'warning',
    field: 'orderCount',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: '주문 없음 — 노출/가격 경쟁력 점검',
    actionType: 'product.check_listing',
    autoExecute: false,
    sortOrder: 41,
  },
  {
    name: 'low-orders',
    displayName: '주문 저조',
    description: '월 주문 5건 미만',
    category: 'order',
    severity: 'info',
    field: 'orderCount',
    operator: 'lt',
    threshold: { value: 5 },
    messageTemplate: '주문 {{value}}건 — 판매 활성화 필요',
    actionType: 'product.create_promotion',
    autoExecute: false,
    sortOrder: 42,
  },
  {
    name: 'high-cancel-rate',
    displayName: '취소율 과다',
    description: '취소/반품율 10% 이상',
    category: 'order',
    severity: 'warning',
    field: 'cancelRate',
    operator: 'gte',
    threshold: { value: 10 },
    messageTemplate: '취소율 {{value}}% — 품질/배송 점검 필요',
    actionType: 'product.review_quality',
    autoExecute: false,
    sortOrder: 43,
  },
  {
    name: 'critical-cancel-rate',
    displayName: '취소율 위험',
    description: '취소/반품율 20% 이상',
    category: 'order',
    severity: 'critical',
    field: 'cancelRate',
    operator: 'gte',
    threshold: { value: 20 },
    messageTemplate: '취소율 {{value}}% — 즉시 원인 분석 필요',
    actionType: 'product.review_quality',
    autoExecute: false,
    sortOrder: 44,
  },
  {
    name: 'return-rate-high',
    displayName: '반품율 경고',
    description: '반품율 5% 이상',
    category: 'order',
    severity: 'warning',
    field: 'returnRate',
    operator: 'gte',
    threshold: { value: 5 },
    messageTemplate: '반품율 {{value}}% — 상품 설명/품질 점검',
    actionType: 'product.review_quality',
    autoExecute: false,
    sortOrder: 45,
  },
  {
    name: 'super-seller-candidate',
    displayName: '핵심상품 후보',
    description: '월 주문 100건 이상 — A등급 승격 후보',
    category: 'order',
    severity: 'info',
    field: 'orderCount',
    operator: 'gte',
    threshold: { value: 100 },
    messageTemplate: '주문 {{value}}건 — A등급 승격 + 재고 확보 검토',
    actionType: 'product.upgrade_grade',
    autoExecute: false,
    sortOrder: 46,
  },
  {
    name: 'order-spike-alert',
    displayName: '주문 급증',
    description: '월 주문 200건 이상 — 재고 주의',
    category: 'order',
    severity: 'warning',
    field: 'orderCount',
    operator: 'gte',
    threshold: { value: 200 },
    messageTemplate: '주문 {{value}}건 급증 — 재고/품질 관리 강화',
    actionType: 'product.create_purchase_order',
    autoExecute: false,
    sortOrder: 47,
  },
  {
    name: 'dormant-product',
    displayName: '휴면 상품',
    description: '주문 0건 + 재고 있음',
    category: 'order',
    severity: 'info',
    field: 'orderCount',
    operator: 'lte',
    threshold: { value: 0 },
    messageTemplate: '주문 없음 + 재고 보유 — 정리 또는 프로모션 검토',
    actionType: 'product.create_promotion',
    autoExecute: false,
    sortOrder: 48,
  },
];
