// 도메인별 에러 코드
export const ErrorCodes = {
  COMMON: {
    NOT_FOUND: 'COMMON_NOT_FOUND',
    BAD_REQUEST: 'COMMON_BAD_REQUEST',
    INTERNAL: 'COMMON_INTERNAL_ERROR',
    DB_ERROR: 'COMMON_DB_ERROR',
    UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
    SERVICE_UNAVAILABLE: 'COMMON_SERVICE_UNAVAILABLE',
  },
  PRODUCT: {
    NOT_FOUND: 'PRODUCT_NOT_FOUND',
    CREATE_FAILED: 'PRODUCT_CREATE_FAILED',
    QUERY_FAILED: 'PRODUCT_QUERY_FAILED',
  },
  ORDER: {
    NO_SELECTION: 'ORDER_NO_SELECTION',
    UNKNOWN_ACTION: 'ORDER_UNKNOWN_ACTION',
  },
  INVENTORY: {
    SYNC_FAILED: 'INVENTORY_SYNC_FAILED',
    NOT_FOUND: 'INVENTORY_NOT_FOUND',
    SELLPIA_SYNC_REQUIRED: 'SELLPIA_SYNC_REQUIRED',
  },
  PURCHASE: {
    ITEM_INACTIVE: 'PURCHASE_ITEM_INACTIVE',
    REFERENCE_INVALID: 'PURCHASE_REFERENCE_INVALID',
    SUBMISSION_RECONCILIATION_REQUIRED:
      'PURCHASE_SUBMISSION_RECONCILIATION_REQUIRED',
    ROCKET_COLLECTION_INCOMPLETE: 'ROCKET_COLLECTION_INCOMPLETE',
  },
  AGENT: {
    NOT_FOUND: 'AGENT_NOT_FOUND',
    EXECUTION_FAILED: 'AGENT_EXECUTION_FAILED',
    BUDGET_EXCEEDED: 'AGENT_BUDGET_EXCEEDED',
    TIMEOUT: 'AGENT_TIMEOUT',
  },
  AI: {
    API_ERROR: 'AI_API_ERROR',
    MODEL_UNAVAILABLE: 'AI_MODEL_UNAVAILABLE',
    GENERATION_FAILED: 'AI_GENERATION_FAILED',
  },
  SOURCING: {
    SCRAPE_FAILED: 'SOURCING_SCRAPE_FAILED',
    PARSE_ERROR: 'SOURCING_PARSE_ERROR',
    NOT_FOUND: 'SOURCING_NOT_FOUND',
  },
  RULE: {
    NOT_FOUND: 'RULE_NOT_FOUND',
    EVALUATION_FAILED: 'RULE_EVALUATION_FAILED',
    INVALID_THRESHOLD: 'RULE_INVALID_THRESHOLD',
  },
  FINANCE: {
    QUERY_FAILED: 'FINANCE_QUERY_FAILED',
    SYNC_FAILED: 'FINANCE_SYNC_FAILED',
  },
} as const;
