import {
  defineCapabilities,
  type CapabilityManifest,
} from '../../../common/capability-manifest';

export const SOURCING_CAPABILITIES = defineCapabilities([
  {
    key: 'sourcing.duplicateCheck',
    ownerDomain: 'sourcing',
    kind: 'resource',
    description: 'Check whether a source product URL already has a sourcing candidate.',
    inputSchema: { sourceUrl: 'string' },
    outputSchema: { duplicate: 'boolean', candidateId: 'string|null' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'both',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_DUPLICATE_CHECK_PORT' },
  },
  {
    key: 'sourcing.scrapeProductUrl',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description: 'Scrape a product URL with the sourcing browser runtime.',
    inputSchema: { sourceUrl: 'string', platform: 'string|undefined' },
    outputSchema: { snapshot: 'SourcingProductSnapshot' },
    effects: ['browser', 'external_io'],
    approval: 'none',
    idempotency: 'recommended',
    visibility: 'both',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_SCRAPE_PRODUCT_URL_PORT' },
  },
  {
    key: 'sourcing.ingestCandidate',
    ownerDomain: 'sourcing',
    kind: 'sink',
    description: 'Persist a validated scraped product snapshot as a sourcing candidate.',
    inputSchema: { snapshot: 'SourcingProductSnapshot' },
    outputSchema: { candidateId: 'string' },
    effects: ['db_write'],
    approval: 'on_write',
    idempotency: 'required',
    visibility: 'both',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_INGEST_CANDIDATE_PORT' },
  },
  {
    key: 'sourcing.scrapeUrlWorkflow',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description: 'Duplicate-check, scrape, ingest, and return the candidate detail link.',
    inputSchema: { sourceUrl: 'string' },
    outputSchema: {
      skipped: 'boolean',
      candidateId: 'string|null',
      href: 'string|null',
      operation: 'OperationRunName|null',
    },
    effects: ['read', 'browser', 'external_io', 'db_write', 'job_enqueue'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'both',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_SCRAPE_URL_WORKFLOW_PORT' },
  },
  {
    key: 'sourcing.retrieveWorkspaceEvidence',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description: 'Retrieve normalized sourcing workspace evidence with stable provenance.',
    inputSchema: { query: 'string', topK: 'number|undefined', days: 'number|undefined' },
    outputSchema: { inputHash: 'string', documentCount: 'number', citationIds: 'string[]', dataGaps: 'string[]' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'recommended',
    visibility: 'agent',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_AGENT_WORKSPACE_READ_CAPABILITY_PORT' },
  },
  {
    key: 'sourcing.inspectRecommendationRun',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description: 'Inspect a persisted sourcing recommendation run and its validation coverage.',
    inputSchema: { recommendationRunId: 'string|undefined' },
    outputSchema: { runId: 'string', status: 'string', itemCount: 'number' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'recommended',
    visibility: 'agent',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_AGENT_WORKSPACE_READ_CAPABILITY_PORT' },
  },
  {
    key: 'sourcing.refreshCollection',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description: 'Start the deterministic sourcing trend collection Operation once.',
    inputSchema: { sources: 'string[]' },
    outputSchema: { operationRunId: 'string', status: 'string' },
    effects: ['db_write', 'external_io', 'job_enqueue'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_COLLECTION_OPERATION_PORT' },
  },
  {
    key: 'sourcing.refreshValidation',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description: 'Build deterministic validation episodes for one recommendation run.',
    inputSchema: { recommendationRunId: 'string' },
    outputSchema: { validationEpisodeIds: 'string[]', missingEvidence: 'string[]' },
    effects: ['db_write'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_AGENT_WORKSPACE_MUTATION_CAPABILITY_PORT' },
  },
  {
    key: 'sourcing.createReviewBatch',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description: 'Create a review-only batch from explicitly versioned selected items.',
    inputSchema: { recommendationRunId: 'string', workspaceKey: 'string', items: 'Selection[]' },
    outputSchema: { reviewBatchId: 'string', itemCount: 'number', status: 'string' },
    effects: ['db_write'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: { type: 'incoming_port', token: 'SOURCING_AGENT_WORKSPACE_MUTATION_CAPABILITY_PORT' },
  },
  {
    key: 'sourcing.collect_shadow_signals',
    ownerDomain: 'sourcing',
    ownerInputPort: 'sourcing.collectShadowSignals',
    kind: 'workflow',
    description: 'Start the fenced market shadow signal Operation once.',
    inputSchema: {},
    outputSchema: { operationRunId: 'string', status: 'string' },
    effects: ['db_write', 'external_io', 'job_enqueue'],
    approval: 'on_write',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: { type: 'incoming_port', token: 'MARKET_SHADOW_COLLECTION_CAPABILITY_PORT' },
  },
] as const satisfies readonly CapabilityManifest[]);

export type SourcingCapabilityKey = (typeof SOURCING_CAPABILITIES)[number]['key'];
