import {
  defineCapabilities,
  type CapabilityManifest,
} from '../../../common/capability-manifest';

export const SOURCING_CAPABILITIES = defineCapabilities([
  {
    key: 'sourcing.duplicateCheck',
    ownerDomain: 'sourcing',
    kind: 'resource',
    description: 'Check whether a source product URL already has a sourcing candidate.',
    inputSchema: { sourceUrl: 'string' },
    outputSchema: { duplicate: 'boolean', candidateId: 'string|null' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'both',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_DUPLICATE_CHECK_PORT',
    },
  },
  {
    key: 'sourcing.scrapeProductUrl',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description: 'Scrape a product URL with the sourcing browser runtime.',
    inputSchema: { sourceUrl: 'string', platform: 'string|undefined' },
    outputSchema: { snapshot: 'SourcingProductSnapshot' },
    effects: ['browser', 'external_io'],
    approval: 'none',
    idempotency: 'recommended',
    visibility: 'both',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_SCRAPE_PRODUCT_URL_PORT',
    },
  },
  {
    key: 'sourcing.ingestCandidate',
    ownerDomain: 'sourcing',
    kind: 'sink',
    description: 'Persist a validated scraped product snapshot as a sourcing candidate.',
    inputSchema: { snapshot: 'SourcingProductSnapshot' },
    outputSchema: { candidateId: 'string' },
    effects: ['db_write'],
    approval: 'on_write',
    idempotency: 'required',
    visibility: 'both',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_INGEST_CANDIDATE_PORT',
    },
  },
  {
    key: 'sourcing.scrapeUrlWorkflow',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description: 'Duplicate-check, scrape, ingest, and return the candidate detail link.',
    inputSchema: { sourceUrl: 'string' },
    outputSchema: { skipped: 'boolean', candidateId: 'string', href: 'string' },
    effects: ['read', 'browser', 'external_io', 'db_write', 'job_enqueue'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'both',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_SCRAPE_URL_WORKFLOW_PORT',
    },
  },
  {
    key: 'market.collect_keyword_category_rankings',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description: 'Collect or replay keyword/category market ranking signals.',
    inputSchema: { keyword: 'string', category: 'string|null', mode: 'stub|replay' },
    outputSchema: { snapshots: 'MarketSignalSnapshot[]' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_DISCOVERY_CAPABILITY_PORT',
    },
  },
  {
    key: 'coupang.match_products',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description: 'Match market opportunities to Coupang listings and seller evidence.',
    inputSchema: { keyword: 'string', category: 'string|null', mode: 'stub|replay' },
    outputSchema: { matches: 'CoupangProductMatch[]' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_DISCOVERY_CAPABILITY_PORT',
    },
  },
  {
    key: 'coupang.collect_tracking_snapshot',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description: 'Capture rank, review, price, seller-count, and recency signals.',
    inputSchema: { keyword: 'string', category: 'string|null', mode: 'stub|replay' },
    outputSchema: { snapshots: 'CoupangTrackingSnapshot[]' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_DISCOVERY_CAPABILITY_PORT',
    },
  },
  {
    key: 'supplier1688.match_products',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description:
      'Match candidate products to 1688 supplier/product/option candidates and enqueue scrape intake when supplier URLs are present.',
    inputSchema: {
      keyword: 'string',
      category: 'string|null',
      mode: 'stub|replay',
      supplierUrl: 'string?',
      supplierUrls: 'string[]?',
    },
    outputSchema: {
      matches: 'SupplierMatch[]',
      scrapeWorkflowRequests: 'number?',
    },
    effects: ['read', 'browser', 'external_io', 'db_write', 'job_enqueue'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_DISCOVERY_CAPABILITY_PORT',
    },
  },
  {
    key: 'sourcing.score_opportunities',
    ownerDomain: 'sourcing',
    kind: 'tool',
    description:
      'Produce explainable demand, novelty, competition, supply-fit, margin, and risk scores.',
    inputSchema: { keyword: 'string', category: 'string|null', mode: 'stub|replay' },
    outputSchema: { scores: 'SourcingOpportunityScore[]' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_DISCOVERY_CAPABILITY_PORT',
    },
  },
  {
    key: 'sourcing.create_recommendation_packet',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description:
      'Create final sourcing recommendation artifacts from market, Coupang, 1688, and score evidence.',
    inputSchema: { keyword: 'string', category: 'string|null', mode: 'stub|replay' },
    outputSchema: { recommendations: 'SourcingRecommendation[]', topScore: 'number' },
    effects: ['read'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_DISCOVERY_CAPABILITY_PORT',
    },
  },
  {
    key: 'product_listing.create_generation_package',
    ownerDomain: 'sourcing',
    kind: 'workflow',
    description:
      'Create a product-generation package for listing prep: sourcing candidate, detail-page job, and thumbnail job.',
    inputSchema: {
      productName: 'string',
      imageUrls: 'string[]',
      category: 'string|null',
      description: 'string|null',
    },
    outputSchema: {
      candidateId: 'string',
      detailGenerationId: 'string|null',
      thumbnailGenerationId: 'string|null',
      contentWorkspaceId: 'string|null',
      href: 'string',
    },
    effects: ['db_write', 'job_enqueue'],
    approval: 'none',
    idempotency: 'required',
    visibility: 'agent',
    entrypoint: {
      type: 'incoming_port',
      token: 'SOURCING_LISTING_PREP_CAPABILITY_PORT',
    },
  },
] as const satisfies readonly CapabilityManifest[]);

export type SourcingCapabilityKey = (typeof SOURCING_CAPABILITIES)[number]['key'];
