import assert from 'node:assert/strict';
import test from 'node:test';
import {
  addedColumns,
  alterTableStatements,
  createdTables,
  splitTopLevel,
  sqlStatements,
  tableConstraint,
  uniqueIndexes,
} from '../_shared/prisma-ddl.mjs';

/**
 * The cutover survey and the PR-time coverage check read `prisma migrate diff`
 * through this module, so a clause it splits wrongly is a blocker both miss.
 */

test('splits statements only at semicolons outside quotes, and drops comments', () => {
  assert.deepEqual(
    sqlStatements(`
-- AlterTable; the comment's semicolon ends nothing
ALTER TABLE "a" ADD COLUMN "note" TEXT DEFAULT 'x;y';
CREATE UNIQUE INDEX "b_key" ON "b"("c") WHERE (label = 'p;q');
`),
    [
      `ALTER TABLE "a" ADD COLUMN "note" TEXT DEFAULT 'x;y'`,
      `CREATE UNIQUE INDEX "b_key" ON "b"("c") WHERE (label = 'p;q')`,
    ],
  );
});

test('skips block comments, nested ones included, like the warnings block Prisma writes into migrations', () => {
  assert.deepEqual(
    sqlStatements(`/*
  Warnings:
  - Added the required column \`slug\` to the \`A\` table; it can't be empty /* nested; */ still a comment.
*/
-- AlterTable
ALTER TABLE "A" ADD COLUMN "slug" TEXT NOT NULL;`),
    ['ALTER TABLE "A" ADD COLUMN "slug" TEXT NOT NULL'],
  );
});

test('splits clauses only at commas outside parentheses, brackets, and quotes', () => {
  assert.deepEqual(
    splitTopLevel(
      `ADD COLUMN "a" DECIMAL(12,6) NOT NULL, ADD COLUMN "b" TEXT[] DEFAULT ARRAY['x,y']::TEXT[], ADD COLUMN "c,d" INT`,
      ',',
    ),
    [
      'ADD COLUMN "a" DECIMAL(12,6) NOT NULL',
      `ADD COLUMN "b" TEXT[] DEFAULT ARRAY['x,y']::TEXT[]`,
      'ADD COLUMN "c,d" INT',
    ],
  );
});

test('keeps doubled quotes inside a literal or an identifier', () => {
  assert.deepEqual(
    splitTopLevel(`'it''s, fine', "say ""hi"", ok", last`, ','),
    [`'it''s, fine'`, `"say ""hi"", ok"`, 'last'],
  );
});

test('reads what each new column gives existing rows', () => {
  const columns = addedColumns(`
ALTER TABLE "t" ADD COLUMN "required" DECIMAL(20,6) NOT NULL,
ADD COLUMN "nullable" VARCHAR(64),
ADD COLUMN "defaulted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "null_default" TEXT DEFAULT NULL,
ADD COLUMN "required_null_default" TEXT NOT NULL DEFAULT NULL,
ADD COLUMN "quoted_default" TEXT NOT NULL DEFAULT 'NOT NULL, 😀',
ADD COLUMN "function_default" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "serial" SERIAL NOT NULL,
ADD COLUMN "big_serial" BIGSERIAL NOT NULL,
ADD COLUMN "identity" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY;
`);
  assert.deepEqual(
    columns.map(({ column, initialSql, requiredWithoutDefault }) => ({ column, initialSql, requiredWithoutDefault })),
    [
      { column: 'required', initialSql: null, requiredWithoutDefault: true },
      { column: 'nullable', initialSql: 'NULL', requiredWithoutDefault: false },
      { column: 'defaulted', initialSql: 'false', requiredWithoutDefault: false },
      { column: 'null_default', initialSql: 'NULL', requiredWithoutDefault: false },
      { column: 'required_null_default', initialSql: null, requiredWithoutDefault: true },
      { column: 'quoted_default', initialSql: `'NOT NULL, 😀'`, requiredWithoutDefault: false },
      { column: 'function_default', initialSql: 'CURRENT_TIMESTAMP', requiredWithoutDefault: false },
      { column: 'serial', initialSql: null, requiredWithoutDefault: false },
      { column: 'big_serial', initialSql: null, requiredWithoutDefault: false },
      { column: 'identity', initialSql: null, requiredWithoutDefault: false },
    ],
  );
  assert.ok(columns.every((column) => column.table === 't'));
  assert.equal(columns[0].definition, 'DECIMAL(20,6) NOT NULL');
});

test('reads column changes, drops, and constraints in one ALTER TABLE', () => {
  const [statement] = alterTableStatements(`
ALTER TABLE "public"."evaluations" DROP COLUMN "old",
ALTER COLUMN "formula_version_id" SET NOT NULL,
ALTER COLUMN "note" DROP NOT NULL,
ALTER COLUMN "calculated_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "formula_key" DROP DEFAULT,
ALTER COLUMN "score" SET DATA TYPE DECIMAL(12,6),
ADD CONSTRAINT "evaluations_pkey" PRIMARY KEY ("id", "organization_id"),
DROP CONSTRAINT "evaluations_old_fkey",
RENAME CONSTRAINT "a" TO "b";
`);
  assert.equal(statement.table, 'evaluations');
  assert.deepEqual(statement.clauses, [
    { action: 'drop-column', column: 'old' },
    { action: 'alter-column', column: 'formula_version_id', change: 'set-not-null' },
    { action: 'alter-column', column: 'note', change: 'drop-not-null' },
    { action: 'alter-column', column: 'calculated_at', change: 'set-default', value: 'CURRENT_TIMESTAMP' },
    { action: 'alter-column', column: 'formula_key', change: 'drop-default' },
    { action: 'alter-column', column: 'score', change: 'set-data-type', value: 'DECIMAL(12,6)' },
    {
      action: 'add-constraint',
      name: 'evaluations_pkey',
      type: 'primary-key',
      columns: ['id', 'organization_id'],
      definition: '',
    },
    { action: 'drop-constraint', name: 'evaluations_old_fkey' },
    { action: 'other', text: 'RENAME CONSTRAINT "a" TO "b"' },
  ]);
});

test('reads a composite foreign key with its referenced columns and options', () => {
  const [statement] = alterTableStatements(
    'ALTER TABLE "snapshots" ADD CONSTRAINT "snapshots_run_fkey" FOREIGN KEY ("organization_id", "ingestion_run_id") '
      + 'REFERENCES "runs"("organization_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;',
  );
  assert.deepEqual(statement.clauses, [{
    action: 'add-constraint',
    name: 'snapshots_run_fkey',
    type: 'foreign-key',
    columns: ['organization_id', 'ingestion_run_id'],
    references: { table: 'runs', columns: ['organization_id', 'id'] },
    definition: 'ON DELETE CASCADE ON UPDATE CASCADE',
  }]);
});

test('reads an unnamed constraint and keeps a CHECK expression whole', () => {
  assert.deepEqual(tableConstraint('UNIQUE ("a", "b")'), {
    name: null,
    type: 'unique',
    columns: ['a', 'b'],
    definition: '',
  });
  assert.deepEqual(tableConstraint('CONSTRAINT "strict_key" UNIQUE NULLS NOT DISTINCT ("a")'), {
    name: 'strict_key',
    type: 'unique',
    columns: ['a'],
    definition: '',
    nullsNotDistinct: true,
  });
  assert.deepEqual(tableConstraint(`CONSTRAINT "status_check" CHECK (status IN ('a', 'b'))`), {
    name: 'status_check',
    type: 'check',
    columns: [],
    definition: `(status IN ('a', 'b'))`,
  });
  assert.equal(tableConstraint('"id" UUID NOT NULL'), null);
});

test('reads unique indexes, keeping expression entries and whatever follows the column list', () => {
  assert.deepEqual(
    uniqueIndexes(`
CREATE UNIQUE INDEX "a_key" ON "public"."a" USING BTREE ("x" DESC, "y" text_pattern_ops) WHERE (kind = 'a,b');
CREATE UNIQUE INDEX "b_key" ON "b"(lower("name"), "org") NULLS NOT DISTINCT;
CREATE INDEX "c_idx" ON "c"("x");
`),
    [
      { name: 'a_key', table: 'a', columns: ['x', 'y'], where: `WHERE (kind = 'a,b')` },
      { name: 'b_key', table: 'b', columns: ['lower("name")', 'org'], where: 'NULLS NOT DISTINCT' },
    ],
  );
});

test('reads created tables with their columns and key constraints, inline ones included', () => {
  assert.deepEqual(
    createdTables(`
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "public"."reviews" (
    "id" UUID NOT NULL,
    "score" DECIMAL(12,6) NOT NULL DEFAULT 0,
    "code" TEXT NOT NULL UNIQUE,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("id", "score")
);

CREATE TABLE IF NOT EXISTS "tags" ("name" TEXT PRIMARY KEY, "label" TEXT);
`),
    [
      {
        table: 'reviews',
        columns: ['id', 'score', 'code'],
        constraints: [
          { name: null, type: 'unique', columns: ['code'], definition: '' },
          { name: 'reviews_pkey', type: 'primary-key', columns: ['id', 'score'], definition: '' },
        ],
      },
      {
        table: 'tags',
        columns: ['name', 'label'],
        constraints: [{ name: null, type: 'primary-key', columns: ['name'], definition: '' }],
      },
    ],
  );
});
