import { Prisma } from '@prisma/client';
import type { MigrationResult } from '../types';

/**
 * One table whose existing rows cannot hold a column the next schema makes
 * required. `db push` adds such a column as NOT NULL with no database default
 * (a Prisma `@default(uuid())` is generated by the client), and PostgreSQL
 * refuses that on a table that still has rows.
 */
export type RequiredColumnCleanup = {
  readonly table: string;
  readonly requiredColumn: string;
  /** Why these rows may go instead of being backfilled. */
  readonly reason: string;
};

export type RequiredColumnCleanupDetails = {
  requiredColumn: string;
  tablePresent: boolean;
  requiredColumnPresent: boolean;
  deletedRows: number;
};

/**
 * The rows every schema/data cutover carries forward under
 * [ADR-0010](../../../docs/adr/0010-schema-cleanup-may-discard-office-data.md)
 * and the data-loss policy in `docs/runbooks/deployment-architecture.md`,
 * keyed by the ADR's words. A cleanup may not delete from these tables, and a
 * delete from a listed table may not cascade into them.
 */
export const ADR_0010_KEPT_TABLES = {
  'users and organizations': ['users', 'organizations', 'organization_memberships'],
  'channel accounts': ['channel_accounts'],
  'confirmed recipes': ['channel_listing_option_inventory_components'],
  orders: ['orders', 'order_line_items'],
  // The Coupang direct receipts and consumptions (ADR-0008), and the Sellpia
  // transmission fence a receipt returns on replay: losing any of them could
  // apply or transmit the same effect twice.
  'transport receipts': [
    'coupang_direct_transport_receipts',
    'coupang_direct_transport_consumptions',
    'sellpia_order_transmission_intents',
    'sellpia_order_transmission_intent_reconciliations',
  ],
} as const satisfies Readonly<Record<string, readonly string[]>>;

const KEPT_TABLES: readonly string[] = Object.values(ADR_0010_KEPT_TABLES).flat();

/** Lowercase identifiers only, so a listed name is safe to inline and quote. */
const PLAIN_IDENTIFIER = /^[a-z_][a-z0-9_]*$/;

type SqlClient = Pick<Prisma.TransactionClient, '$queryRaw' | '$executeRaw'>;

type ShapeRow = {
  table_name: string;
  table_present: boolean;
  required_column_present: boolean;
};

type KeptTableReachRow = {
  listed_table: string;
  kept_table: string;
  action: string;
};

/** Throws for a list this helper must not run: nothing has touched the database yet. */
export function assertRequiredColumnCleanups(cleanups: readonly RequiredColumnCleanup[]): void {
  const listed = new Set<string>();
  for (const { table, requiredColumn, reason } of cleanups) {
    if (!PLAIN_IDENTIFIER.test(table) || !PLAIN_IDENTIFIER.test(requiredColumn)) {
      throw new Error(`Required-column cleanup needs plain lowercase identifiers, got ${JSON.stringify(`${table}.${requiredColumn}`)}.`);
    }
    if (KEPT_TABLES.includes(table)) {
      throw new Error(`Required-column cleanup refuses ${table}: ADR-0010 carries its rows through every cutover.`);
    }
    if (listed.has(table)) {
      throw new Error(`Required-column cleanup lists ${table} more than once.`);
    }
    if (reason.trim() === '') {
      throw new Error(`Required-column cleanup for ${table} needs a reason.`);
    }
    listed.add(table);
  }
}

/**
 * Checks a migration's list when its module loads, so a list that names a kept
 * table stops the migration runner before any migration starts.
 */
export function defineRequiredColumnCleanups<const T extends readonly RequiredColumnCleanup[]>(
  cleanups: T,
): T {
  assertRequiredColumnCleanups(cleanups);
  for (const cleanup of cleanups) Object.freeze(cleanup);
  Object.freeze(cleanups);
  return cleanups;
}

/**
 * Deletes every row of each listed table that still lacks its required column,
 * for a pre-schema migration under the data-loss policy (ADR-0010).
 *
 * - The list is checked again, and the catalog is asked whether deleting from a
 *   listed table would cascade into, or null a reference in, a kept table.
 *   Either refusal comes before any delete.
 * - A table the database does not have is skipped.
 * - A table that already has its required column is on the new schema, so
 *   nothing is deleted from it; a run after `db push` affects no rows.
 * - Any other table loses all of its rows, across every organization.
 *
 * Details are keyed by table, in list order. `affectedRows` is the total.
 */
export async function removeRowsBlockingRequiredColumns(
  tx: SqlClient,
  cleanups: readonly RequiredColumnCleanup[],
): Promise<MigrationResult> {
  assertRequiredColumnCleanups(cleanups);
  const tables = cleanups.map((cleanup) => cleanup.table);
  const columns = cleanups.map((cleanup) => cleanup.requiredColumn);

  const reaches = await tx.$queryRaw<KeptTableReachRow[]>`
    WITH RECURSIVE deleted (listed_table, table_oid, path) AS (
      SELECT c.relname::text, c.oid, ARRAY[c.relname::text]
      FROM pg_class c
      WHERE c.relnamespace = to_regnamespace(current_schema())
        AND c.relkind IN ('r', 'p')
        AND c.relname::text = ANY(${tables}::text[])
      UNION ALL
      SELECT deleted.listed_table, child.oid, deleted.path || child.relname::text
      FROM deleted
      JOIN pg_constraint fk
        ON fk.contype = 'f' AND fk.confrelid = deleted.table_oid AND fk.confdeltype = 'c'
      JOIN pg_class child ON child.oid = fk.conrelid
      WHERE NOT (child.relname::text = ANY(deleted.path))
    )
    SELECT DISTINCT
      deleted.listed_table,
      touched.relname::text AS kept_table,
      fk.confdeltype::text AS action
    FROM deleted
    JOIN pg_constraint fk
      ON fk.contype = 'f' AND fk.confrelid = deleted.table_oid AND fk.confdeltype IN ('c', 'n', 'd')
    JOIN pg_class touched ON touched.oid = fk.conrelid
    WHERE touched.relname::text = ANY(${[...KEPT_TABLES]}::text[])
    ORDER BY 1, 2
  `;
  if (reaches.length > 0) {
    const found = reaches
      .map((reach) => `${reach.listed_table} -> ${reach.kept_table} (on delete ${deleteAction(reach.action)})`)
      .join(', ');
    throw new Error(`Required-column cleanup refuses deletes that reach ADR-0010 kept tables: ${found}.`);
  }

  const shapes = await tx.$queryRaw<ShapeRow[]>`
    SELECT
      entry.table_name,
      EXISTS (
        SELECT 1
        FROM information_schema.tables t
        WHERE t.table_schema = current_schema()
          AND t.table_type = 'BASE TABLE'
          AND t.table_name::text = entry.table_name
      ) AS table_present,
      EXISTS (
        SELECT 1
        FROM information_schema.columns c
        WHERE c.table_schema = current_schema()
          AND c.table_name::text = entry.table_name
          AND c.column_name::text = entry.column_name
      ) AS required_column_present
    FROM unnest(${tables}::text[], ${columns}::text[]) AS entry(table_name, column_name)
  `;
  const shapeByTable = new Map(shapes.map((shape) => [shape.table_name, shape]));

  let affectedRows = 0;
  const details: Record<string, RequiredColumnCleanupDetails> = {};
  // The list drives every delete; a catalog row for any other table is ignored.
  for (const cleanup of cleanups) {
    const shape = shapeByTable.get(cleanup.table);
    const tablePresent = shape?.table_present === true;
    const requiredColumnPresent = shape?.required_column_present === true;
    const deletedRows = tablePresent && !requiredColumnPresent
      ? await tx.$executeRaw`DELETE FROM ${requiredColumnCleanupTable(cleanup.table, cleanups)}`
      : 0;
    affectedRows += deletedRows;
    details[cleanup.table] = {
      requiredColumn: cleanup.requiredColumn,
      tablePresent,
      requiredColumnPresent,
      deletedRows,
    };
  }

  return { affectedRows, details };
}

/** Inlines a table only when the list names it and ADR-0010 does not keep it. */
export function requiredColumnCleanupTable(
  table: string,
  cleanups: readonly RequiredColumnCleanup[],
): Prisma.Sql {
  if (
    !PLAIN_IDENTIFIER.test(table)
    || KEPT_TABLES.includes(table)
    || !cleanups.some((cleanup) => cleanup.table === table)
  ) {
    throw new Error(`Unexpected required-column cleanup table: ${JSON.stringify(table)}`);
  }
  return Prisma.raw(`"${table}"`);
}

function deleteAction(code: string): string {
  if (code === 'c') return 'cascade';
  if (code === 'n') return 'set null';
  if (code === 'd') return 'set default';
  return code;
}
