import { Prisma } from '@prisma/client';
import type { MigrationResult } from '../types';
import {
  activeDependentRowSteps,
  applyDependentRowRemoval,
  type ApprovalEntry,
  assertDependentRowSteps,
  assertOwnerApprovalDeclared,
  assertOwnerApprovals,
  type DependentRowStep,
  foreignKeysInto,
  isPlainIdentifier,
  KEPT_TABLES,
  type OwnerApproval,
  planDependentRowRemoval,
  quotedIdentifier,
  type SqlClient,
  tablesDeletedBy,
  unique,
} from './dependent-row-removal';

/**
 * One table whose existing rows cannot hold, or cannot be read without, a
 * column the next schema makes required. `db push` adds a required column
 * with no database default (a Prisma `@default(uuid())` is generated by the
 * client) only to a table without rows. A required column with a database
 * default fits old rows, so a table is listed for one only when the new
 * release cannot read rows written before the column existed.
 */
export type RequiredColumnCleanup = {
  readonly table: string;
  readonly requiredColumn: string;
  /** Why these rows may go instead of being backfilled. */
  readonly reason: string;
  /**
   * Every foreign key into a table this entry deletes from, in execution
   * order. A step whose foreign key the database does not have is skipped.
   */
  readonly dependents?: readonly DependentRowStep[];
  /** Required exactly when a dependent step deletes human-entered rows. */
  readonly ownerApproval?: OwnerApproval;
};

export type RequiredColumnCleanupDetails = {
  requiredColumn: string;
  tablePresent: boolean;
  requiredColumnPresent: boolean;
  deletedRows: number;
  /** Rows deleted first from each dependent table, when the entry declares delete steps. */
  dependentRows?: Record<string, number>;
  /** References cleared by `table.column`, when the entry declares unlink steps. */
  unlinkedRows?: Record<string, number>;
};

type ShapeRow = {
  table_name: string;
  table_present: boolean;
  required_column_present: boolean;
};

type KeptTableReachRow = {
  listed_table: string;
  kept_table: string;
  action: string;
};

type IdRow = { id: string };

/** Throws for a list this helper must not run: nothing has touched the database yet. */
export function assertRequiredColumnCleanups(cleanups: readonly RequiredColumnCleanup[]): void {
  const listed = new Set<string>();
  for (const cleanup of cleanups) {
    const { table, requiredColumn, reason } = cleanup;
    if (!isPlainIdentifier(table) || !isPlainIdentifier(requiredColumn)) {
      throw new Error(`Required-column cleanup needs plain lowercase identifiers, got ${JSON.stringify(`${table}.${requiredColumn}`)}.`);
    }
    if (KEPT_TABLES.includes(table)) {
      throw new Error(`Required-column cleanup refuses ${table}: ADR-0010 carries its rows through every cutover.`);
    }
    if (listed.has(table)) {
      throw new Error(`Required-column cleanup lists ${table} more than once.`);
    }
    if (reason.trim() === '') {
      throw new Error(`Required-column cleanup for ${table} needs a reason.`);
    }
    assertDependentRowSteps(`Required-column cleanup for ${table}`, table, cleanup.dependents);
    assertOwnerApprovalDeclared(approvalEntry(cleanup));
    listed.add(table);
  }
}

/**
 * Checks a migration's list when its module loads, so a list that names a kept
 * table stops the migration runner before any migration starts. A pending
 * approval does not stop the module from loading; it stops the run.
 */
export function defineRequiredColumnCleanups<const T extends readonly RequiredColumnCleanup[]>(
  cleanups: T,
): T {
  assertRequiredColumnCleanups(cleanups);
  for (const cleanup of cleanups) {
    for (const step of cleanup.dependents ?? []) {
      if (step.action === 'unlink' && step.alsoClear) Object.freeze(step.alsoClear);
      Object.freeze(step);
    }
    if (cleanup.dependents) Object.freeze(cleanup.dependents);
    if (typeof cleanup.ownerApproval === 'object') Object.freeze(cleanup.ownerApproval);
    Object.freeze(cleanup);
  }
  Object.freeze(cleanups);
  return cleanups;
}

/** The entry as the owner-approval gate reads it. */
export function approvalEntry(cleanup: RequiredColumnCleanup): ApprovalEntry {
  return {
    label: `Required-column cleanup for ${cleanup.table}`,
    dependents: cleanup.dependents,
    ownerApproval: cleanup.ownerApproval,
  };
}

/**
 * Deletes every row of each listed table that still lacks its required column,
 * for a pre-schema migration under the data-loss policy (ADR-0010).
 *
 * - The list is checked again, and a pending owner approval stops the run.
 * - The catalog is asked whether deleting from a listed or dependent table
 *   would cascade into, or null a reference in, a kept table. Every foreign key
 *   into a table an entry deletes from must be a declared dependent step. Both
 *   refusals come before any delete.
 * - A table the database does not have is skipped.
 * - A table that already has its required column is on the new schema, so
 *   nothing is deleted from it; a run after `db push` affects no rows.
 * - Any other table loses all of its rows, across every organization, after
 *   its dependent rows: deleted children first, cleared references, and a
 *   refusal when a kept row that cannot be unlinked points at one.
 *
 * Details are keyed by table, in list order. `affectedRows` is the total of
 * deleted and unlinked rows.
 */
export async function removeRowsBlockingRequiredColumns(
  tx: SqlClient,
  cleanups: readonly RequiredColumnCleanup[],
): Promise<MigrationResult> {
  assertRequiredColumnCleanups(cleanups);
  assertOwnerApprovals(cleanups.map(approvalEntry));
  const tables = cleanups.map((cleanup) => cleanup.table);
  const columns = cleanups.map((cleanup) => cleanup.requiredColumn);
  const deletedTables = unique(cleanups.flatMap((cleanup) => tablesDeletedBy(cleanup.table, cleanup.dependents)));

  const reaches = await tx.$queryRaw<KeptTableReachRow[]>`
    WITH RECURSIVE deleted (listed_table, table_oid, path) AS (
      SELECT c.relname::text, c.oid, ARRAY[c.relname::text]
      FROM pg_class c
      WHERE c.relnamespace = to_regnamespace(current_schema())
        AND c.relkind IN ('r', 'p')
        AND c.relname::text = ANY(${deletedTables}::text[])
      UNION ALL
      SELECT deleted.listed_table, child.oid, deleted.path || child.relname::text
      FROM deleted
      JOIN pg_constraint fk
        ON fk.contype = 'f' AND fk.confrelid = deleted.table_oid AND fk.confdeltype = 'c'
      JOIN pg_class child ON child.oid = fk.conrelid
      WHERE NOT (child.relname::text = ANY(deleted.path))
    )
    SELECT DISTINCT
      deleted.listed_table,
      touched.relname::text AS kept_table,
      fk.confdeltype::text AS action
    FROM deleted
    JOIN pg_constraint fk
      ON fk.contype = 'f' AND fk.confrelid = deleted.table_oid AND fk.confdeltype IN ('c', 'n', 'd')
    JOIN pg_class touched ON touched.oid = fk.conrelid
    WHERE touched.relname::text = ANY(${[...KEPT_TABLES]}::text[])
    ORDER BY 1, 2
  `;
  if (reaches.length > 0) {
    const found = reaches
      .map((reach) => `${reach.listed_table} -> ${reach.kept_table} (on delete ${deleteAction(reach.action)})`)
      .join(', ');
    throw new Error(`Required-column cleanup refuses deletes that reach ADR-0010 kept tables: ${found}.`);
  }

  const shapes = await tx.$queryRaw<ShapeRow[]>`
    SELECT
      entry.table_name,
      EXISTS (
        SELECT 1
        FROM information_schema.tables t
        WHERE t.table_schema = current_schema()
          AND t.table_type = 'BASE TABLE'
          AND t.table_name::text = entry.table_name
      ) AS table_present,
      EXISTS (
        SELECT 1
        FROM information_schema.columns c
        WHERE c.table_schema = current_schema()
          AND c.table_name::text = entry.table_name
          AND c.column_name::text = entry.column_name
      ) AS required_column_present
    FROM unnest(${tables}::text[], ${columns}::text[]) AS entry(table_name, column_name)
  `;
  const shapeByTable = new Map(shapes.map((shape) => [shape.table_name, shape]));

  // The list drives every delete; a catalog row for any other table is ignored.
  const plans = cleanups.map((cleanup) => {
    const shape = shapeByTable.get(cleanup.table);
    const tablePresent = shape?.table_present === true;
    const requiredColumnPresent = shape?.required_column_present === true;
    return { cleanup, tablePresent, requiredColumnPresent, deletes: tablePresent && !requiredColumnPresent };
  });

  // Every refusal the catalog can give comes before the first delete.
  const deleting = plans.filter((plan) => plan.deletes).map((plan) => plan.cleanup);
  const foreignKeys = deleting.length === 0
    ? []
    : await foreignKeysInto(tx, unique(deleting.flatMap((cleanup) => tablesDeletedBy(cleanup.table, cleanup.dependents))));
  const activeSteps = new Map(deleting.map((cleanup) => [
    cleanup.table,
    activeDependentRowSteps(`Required-column cleanup for ${cleanup.table}`, cleanup.table, cleanup.dependents, foreignKeys),
  ]));

  let affectedRows = 0;
  const details: Record<string, RequiredColumnCleanupDetails> = {};
  for (const { cleanup, tablePresent, requiredColumnPresent, deletes } of plans) {
    const declared = cleanup.dependents ?? [];
    const dependentRows: Record<string, number> = {};
    const unlinkedRows: Record<string, number> = {};
    let deletedRows = 0;
    if (deletes) {
      const steps = activeSteps.get(cleanup.table) ?? [];
      if (steps.length > 0) {
        const rootIds = (await tx.$queryRaw<IdRow[]>`
          SELECT id::text AS id FROM ${quotedIdentifier(cleanup.table)}
        `).map((row) => row.id);
        const plan = await planDependentRowRemoval(tx, cleanup.table, rootIds, steps);
        if (plan.blocked) {
          throw new Error(
            `Required-column cleanup for ${cleanup.table} cannot delete rows that ADR-0010 kept rows reference: `
              + `${Object.entries(plan.keptReferences).map(([link, rows]) => `${link} (${rows})`).join(', ')}.`,
          );
        }
        const counts = await applyDependentRowRemoval(tx, plan, steps);
        Object.assign(dependentRows, counts.dependentRows);
        Object.assign(unlinkedRows, counts.unlinkedRows);
      }
      deletedRows = await tx.$executeRaw`DELETE FROM ${requiredColumnCleanupTable(cleanup.table, cleanups)}`;
    }
    affectedRows += deletedRows + sum(dependentRows) + sum(unlinkedRows);
    details[cleanup.table] = {
      requiredColumn: cleanup.requiredColumn,
      tablePresent,
      requiredColumnPresent,
      deletedRows,
      ...(declared.some((step) => step.action === 'delete') ? { dependentRows } : {}),
      ...(declared.some((step) => step.action === 'unlink') ? { unlinkedRows } : {}),
    };
  }

  return { affectedRows, details };
}

/** Inlines a table only when the list names it and ADR-0010 does not keep it. */
export function requiredColumnCleanupTable(
  table: string,
  cleanups: readonly RequiredColumnCleanup[],
): Prisma.Sql {
  if (
    !isPlainIdentifier(table)
    || KEPT_TABLES.includes(table)
    || !cleanups.some((cleanup) => cleanup.table === table)
  ) {
    throw new Error(`Unexpected required-column cleanup table: ${JSON.stringify(table)}`);
  }
  return Prisma.raw(`"${table}"`);
}

function deleteAction(code: string): string {
  if (code === 'c') return 'cascade';
  if (code === 'n') return 'set null';
  if (code === 'd') return 'set default';
  return code;
}

function sum(counts: Readonly<Record<string, number>>): number {
  return Object.values(counts).reduce((total, count) => total + count, 0);
}
