#!/usr/bin/env bash
# Shared root-import non-regression scanner.
#
# Goal: stop `from '@kiditem/shared'` ROOT imports from growing in
# apps/server/src and apps/web/src. The current set of root imports is
# captured in scripts/.shared-root-imports-baseline.txt and treated as an
# upper bound. Subpath imports (`from '@kiditem/shared/product'`,
# `'@kiditem/shared/errors'`, etc.) are the migration target and are NOT
# counted by this scanner.
#
# Policy
#   - For every file under the scan paths, count lines matching
#     `from '@kiditem/shared'` (root only — subpath imports excluded).
#   - Compare the per-file count against the baseline:
#       current count >  baseline count  → FAIL (regression)
#       current count <= baseline count  → PASS (removals tolerated)
#       file in current, NOT in baseline → FAIL (new file added a root import)
#       file in baseline, NOT in current → PASS (baseline entry decayed; OK)
#
# Removal tolerance
#   The scanner intentionally treats the baseline as a ceiling, not a floor.
#   Migration PRs that move root imports to subpaths can land in parallel
#   without coordinating baseline edits, and their drops are recorded as a
#   "ratchet hint" the next time the baseline is regenerated.
#
# Regenerate the baseline (after a legitimate migration ratchet):
#   bash scripts/check-shared-root-imports.sh --regenerate
#
# Bash 3.2 compatible (macOS default). Requires ripgrep (rg).

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
BASELINE_FILE="$SCRIPT_DIR/.shared-root-imports-baseline.txt"

SCAN_PATHS=(
  "$REPO_ROOT/apps/server/src"
  "$REPO_ROOT/apps/web/src"
)

if ! command -v rg >/dev/null 2>&1; then
  echo "ERROR: ripgrep (rg) is required. Install: brew install ripgrep" >&2
  exit 2
fi

# Root pattern — closing quote IMMEDIATELY after `shared`. This excludes
# subpath imports such as `'@kiditem/shared/product'`, which are the target
# shape for new code.
ROOT_IMPORT_PATTERN="from ['\"]@kiditem/shared['\"]"

# ── Helpers ────────────────────────────────────────────────────────────────

# Emit `<count> <repo-relative-path>` for every file under SCAN_PATHS that
# has at least one root import, sorted by path. rg -c reports `path:count`
# per file with matches.
compute_current_counts() {
  local path abs count rel
  {
    for path in "${SCAN_PATHS[@]}"; do
      [ -d "$path" ] || continue
      rg -c "$ROOT_IMPORT_PATTERN" "$path" \
        --type ts \
        --type-add 'tsx:*.tsx' --type tsx \
        --glob '!**/.next/**' \
        --glob '!**/dist/**' \
        --glob '!**/node_modules/**' \
        2>/dev/null || true
    done
  } | while IFS=':' read -r abs count; do
    [ -z "$abs" ] && continue
    rel="${abs#"$REPO_ROOT"/}"
    printf '%s %s\n' "$count" "$rel"
  done | LC_ALL=C sort -k2,2
}

# ── Regenerate mode ────────────────────────────────────────────────────────

if [ "${1:-}" = "--regenerate" ]; then
  TMP_OUT=$(mktemp)
  trap 'rm -f "$TMP_OUT"' EXIT
  {
    cat <<'HEADER'
# scripts/.shared-root-imports-baseline.txt
#
# Shared root-import ceiling: per-file count of `from '@kiditem/shared'`
# ROOT imports (subpath imports such as `@kiditem/shared/product` are NOT
# counted). Generated by `bash scripts/check-shared-root-imports.sh
# --regenerate`. Removal-tolerant: files whose count drops do not require a
# regeneration to keep the gate green; regenerate when ratcheting the ceiling
# down.
#
# Format per non-comment line: <count> <repo-relative-path>
HEADER
    compute_current_counts
  } > "$TMP_OUT"
  mv "$TMP_OUT" "$BASELINE_FILE"
  trap - EXIT
  count=$(grep -cv '^[[:space:]]*\(#\|$\)' "$BASELINE_FILE" || true)
  echo "✅ baseline written: $BASELINE_FILE"
  echo "   $count file entries"
  exit 0
fi

# ── Verify mode ────────────────────────────────────────────────────────────

if [ ! -f "$BASELINE_FILE" ]; then
  echo "ERROR: baseline file not found: $BASELINE_FILE" >&2
  echo "  Generate with: bash scripts/check-shared-root-imports.sh --regenerate" >&2
  exit 2
fi

# Load baseline into parallel arrays. Bash 3.2 has no associative arrays.
BASELINE_PATHS=()
BASELINE_COUNTS=()
while IFS= read -r raw_line || [ -n "$raw_line" ]; do
  trimmed="${raw_line#"${raw_line%%[![:space:]]*}"}"
  trimmed="${trimmed%"${trimmed##*[![:space:]]}"}"
  case "$trimmed" in
    ''|\#*) continue ;;
  esac
  count_part="${trimmed%%[[:space:]]*}"
  rest="${trimmed#"$count_part"}"
  rest="${rest#"${rest%%[![:space:]]*}"}"
  path_part="$rest"
  case "$count_part" in
    ''|*[!0-9]*)
      echo "ERROR: malformed baseline line (count not numeric): $raw_line" >&2
      exit 2
      ;;
  esac
  if [ -z "$path_part" ]; then
    echo "ERROR: malformed baseline line (missing path): $raw_line" >&2
    exit 2
  fi
  BASELINE_PATHS+=("$path_part")
  BASELINE_COUNTS+=("$count_part")
done < "$BASELINE_FILE"

baseline_count_for() {
  local target="$1" i
  for i in "${!BASELINE_PATHS[@]}"; do
    if [ "${BASELINE_PATHS[$i]}" = "$target" ]; then
      printf '%s' "${BASELINE_COUNTS[$i]}"
      return 0
    fi
  done
  printf '0'
}

echo "🔍 check:shared-root-imports — scanning apps/server/src + apps/web/src"

NEW_FILES=()
GROWN_FILES=()
TOTAL_CURRENT=0
TOTAL_CURRENT_FILES=0

# Collect current scan into temp file because we iterate twice (totals + diff).
CURRENT_TMP=$(mktemp)
trap 'rm -f "$CURRENT_TMP"' EXIT
compute_current_counts > "$CURRENT_TMP"

while IFS= read -r entry; do
  [ -z "$entry" ] && continue
  count="${entry%% *}"
  rel="${entry#* }"
  TOTAL_CURRENT=$((TOTAL_CURRENT + count))
  TOTAL_CURRENT_FILES=$((TOTAL_CURRENT_FILES + 1))
  baseline=$(baseline_count_for "$rel")
  if [ "$baseline" = "0" ]; then
    NEW_FILES+=("$count $rel")
  elif [ "$count" -gt "$baseline" ]; then
    GROWN_FILES+=("$rel: $baseline → $count")
  fi
done < "$CURRENT_TMP"

TOTAL_BASELINE=0
if [ "${#BASELINE_COUNTS[@]}" -gt 0 ]; then
  for c in "${BASELINE_COUNTS[@]}"; do
    TOTAL_BASELINE=$((TOTAL_BASELINE + c))
  done
fi

echo "  baseline: $TOTAL_BASELINE root import line(s) across ${#BASELINE_PATHS[@]} file(s)"
echo "  current : $TOTAL_CURRENT root import line(s) across $TOTAL_CURRENT_FILES file(s)"

FAIL=0

if [ ${#NEW_FILES[@]} -gt 0 ]; then
  echo ""
  echo "❌ FAIL: ${#NEW_FILES[@]} file(s) NOT in baseline added a root \`@kiditem/shared\` import:"
  for h in "${NEW_FILES[@]}"; do
    echo "   - $h"
  done
  FAIL=1
fi

if [ ${#GROWN_FILES[@]} -gt 0 ]; then
  echo ""
  echo "❌ FAIL: ${#GROWN_FILES[@]} existing file(s) grew root import count above baseline:"
  for h in "${GROWN_FILES[@]}"; do
    echo "   - $h"
  done
  FAIL=1
fi

if [ "$FAIL" -gt 0 ]; then
  cat <<'GUIDE'

  Shared root-import policy
    - New code MUST use subpath imports, e.g.
        import { Foo } from '@kiditem/shared/product';
        import { ErrorCodes } from '@kiditem/shared/errors';
      The root barrel `from '@kiditem/shared'` is frozen to its current
      consumers; new files and new lines are blocked.
    - The baseline (scripts/.shared-root-imports-baseline.txt) is an upper
      bound. Removals are tolerated and do NOT require regeneration; this
      is what lets migration PRs run in parallel.
    - If you legitimately ratcheted the ceiling down (migrated existing root
      imports to subpaths) and want to lock the new lower bound, regenerate:

        bash scripts/check-shared-root-imports.sh --regenerate

      Commit the updated baseline alongside the migration.

  See packages/shared/AGENTS.md "Reconstruction Export Policy" and the
  root AGENTS.md "Shared contract".
GUIDE
  exit 1
fi

# Hint when migrations have left the ceiling higher than current usage —
# does not fail the gate, just suggests a ratchet.
if [ "$TOTAL_CURRENT" -lt "$TOTAL_BASELINE" ]; then
  diff=$((TOTAL_BASELINE - TOTAL_CURRENT))
  echo ""
  echo "ℹ️  baseline ceiling is $diff line(s) higher than current usage."
  echo "   Optional: regenerate to ratchet the ceiling down:"
  echo "     bash scripts/check-shared-root-imports.sh --regenerate"
fi

echo ""
echo "✅ PASS: no new root \`@kiditem/shared\` imports above baseline."
exit 0
